In [1]:
import pandas as pd

In [2]:
file_path = "../data/raw/variant_summary.txt"

df = pd.read_csv(file_path, sep="\t")

C:\Users\limhe\AppData\Local\Temp\ipykernel_34404\3817189217.py:3: DtypeWarning: Columns (0: Chromosome) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path, sep="\t")

General Exploration

In [3]:
pd.set_option("display.max_columns", None)
df.head(20)

,#AlleleID,Type,Name,GeneID,GeneSymbol,HGNC_ID,ClinicalSignificance,ClinSigSimple,LastEvaluated,RS# (dbSNP),nsv/esv (dbVar),RCVaccession,PhenotypeIDS,PhenotypeList,Origin,OriginSimple,Assembly,ChromosomeAccession,Chromosome,Start,Stop,ReferenceAllele,AlternateAllele,Cytogenetic,ReviewStatus,NumberSubmitters,Guidelines,TestedInGTR,OtherIDs,SubmitterCategories,VariationID,PositionVCF,ReferenceAlleleVCF,AlternateAlleleVCF,SomaticClinicalImpact,SomaticClinicalImpactLastEvaluated,ReviewStatusClinicalImpact,Oncogenicity,OncogenicityLastEvaluated,ReviewStatusOncogenicity,SCVsForAggregateGermlineClassification,SCVsForAggregateSomaticClinicalImpact,SCVsForAggregateOncogenicityClassification
0,15041,Indel,NM_014855.3(AP5Z1):c.80_83delinsTGCTGTAAACTGTA...,9907,AP5Z1,HGNC:22197,Pathogenic/Likely pathogenic,1,"Dec 17, 2024",397704705,-,RCV000000012|RCV005255549|RCV004998069,"MONDO:MONDO:0013342,MedGen:C3150901,OMIM:61364...",Hereditary spastic paraplegia 48|Macular dystr...,germline;unknown,germline,GRCh37,NC_000007.13,7,4820844,4820847,na,na,7p22.1,"criteria provided, multiple submitters, no con...",4,-,N,"ClinGen:CA215070,OMIM:613653.0001",3,2,4820844,GGAT,TGCTGTAAACTGTAACTGTAAA,-,-,-,-,-,-,SCV001451119|SCV005622007|SCV005909190,-,-
1,15041,Indel,NM_014855.3(AP5Z1):c.80_83delinsTGCTGTAAACTGTA...,9907,AP5Z1,HGNC:22197,Pathogenic/Likely pathogenic,1,"Dec 17, 2024",397704705,-,RCV000000012|RCV005255549|RCV004998069,"MONDO:MONDO:0013342,MedGen:C3150901,OMIM:61364...",Hereditary spastic paraplegia 48|Macular dystr...,germline;unknown,germline,GRCh38,NC_000007.14,7,4781213,4781216,na,na,7p22.1,"criteria provided, multiple submitters, no con...",4,-,N,"ClinGen:CA215070,OMIM:613653.0001",3,2,4781213,GGAT,TGCTGTAAACTGTAACTGTAAA,-,-,-,-,-,-,SCV001451119|SCV005622007|SCV005909190,-,-
2,15042,Deletion,NM_014855.3(AP5Z1):c.1413_1426del (p.Leu473fs),9907,AP5Z1,HGNC:22197,Pathogenic,1,"Jun 29, 2010",397704709,-,RCV000000013,"MONDO:MONDO:0013342,MedGen:C3150901,OMIM:61364...",Hereditary spastic paraplegia 48,germline,germline,GRCh37,NC_000007.13,7,4827361,4827374,na,na,7p22.1,no assertion criteria provided,1,-,N,"ClinGen:CA215072,OMIM:613653.0002",1,3,4827360,GCTGCTGGACCTGCC,G,-,-,-,-,-,-,SCV000020156,-,-
3,15042,Deletion,NM_014855.3(AP5Z1):c.1413_1426del (p.Leu473fs),9907,AP5Z1,HGNC:22197,Pathogenic,1,"Jun 29, 2010",397704709,-,RCV000000013,"MONDO:MONDO:0013342,MedGen:C3150901,OMIM:61364...",Hereditary spastic paraplegia 48,germline,germline,GRCh38,NC_000007.14,7,4787730,4787743,na,na,7p22.1,no assertion criteria provided,1,-,N,"ClinGen:CA215072,OMIM:613653.0002",1,3,4787729,GCTGCTGGACCTGCC,G,-,-,-,-,-,-,SCV000020156,-,-
4,15043,single nucleotide variant,NM_014630.3(ZNF592):c.3136G>A (p.Gly1046Arg),9640,ZNF592,HGNC:28986,Uncertain significance,0,"Jun 29, 2015",150829393,-,RCV000000014,"MONDO:MONDO:0033005,MedGen:C4551772,OMIM:25130...",Galloway-Mowat syndrome 1,germline,germline,GRCh37,NC_000015.9,15,85342440,85342440,na,na,15q25.3,no assertion criteria provided,1,-,N,"ClinGen:CA210674,UniProtKB:Q92610#VAR_064583,O...",1,4,85342440,G,A,-,-,-,-,-,-,SCV000020157,-,-
5,15043,single nucleotide variant,NM_014630.3(ZNF592):c.3136G>A (p.Gly1046Arg),9640,ZNF592,HGNC:28986,Uncertain significance,0,"Jun 29, 2015",150829393,-,RCV000000014,"MONDO:MONDO:0033005,MedGen:C4551772,OMIM:25130...",Galloway-Mowat syndrome 1,germline,germline,GRCh38,NC_000015.10,15,84799209,84799209,na,na,15q25.3,no assertion criteria provided,1,-,N,"ClinGen:CA210674,UniProtKB:Q92610#VAR_064583,O...",1,4,84799209,G,A,-,-,-,-,-,-,SCV000020157,-,-
6,15044,single nucleotide variant,NM_017547.4(FOXRED1):c.694C>T (p.Gln232Ter),55572,FOXRED1,HGNC:26927,Pathogenic,1,"Aug 17, 2025",267606829,-,RCV000000015|RCV000578659|RCV001194045|RCV0033...,"MONDO:MONDO:0032624,MedGen:C4748791,OMIM:61824...","Mitochondrial complex I deficiency, nuclear ty...",germline,germline,GRCh37,NC_000011.9,11,126145284,126145284,na,na,11q24.2,"criteria provided, multiple submitters, no con...",6,-,N,"ClinGen:CA113792,OMIM:613622.0001",3,5,126145284,C,T,-,-,-,-,-,-,SCV000680696|SCV001363290|SCV002793147|SCV0029...,-,-
7,15044,single nucleotide variant,NM_017547.4(FOXRED1):c.694C>T (p.Gln232Ter),55572,FOXRED1,HGNC:26927,Pathogenic,1,"Aug 17, 2025",267606829,-,RCV000000015|RCV000578659|RCV001194045|RCV0033...,"MONDO:MONDO:0032624,MedGen:C4748791,OMIM:61824...","Mitochondrial complex I deficiency, nuclear ty...",germline,germline,GRCh38,NC_000011.10,11,126275389,126275389,na,na,11q24.2,"criteria provided, multiple submitters, no con...",6,-,N,"ClinGen:CA113792,OMIM:613622.0001",3,5,126275389,C,T,-,-,-,-,-,-,SCV000680696|SCV001363290|SCV002793147|SCV0029...,-,-
8,15045,single nucleotide variant,NM_017547.4(FOXRED1):c.1289A>G (p.Asn430Ser),55572,FOXRED1,HGNC:26927,Likely pathogenic,1,"Jun 06, 2024",267606830,-,RCV000000016,"MONDO:MONDO:0032624,MedGen:C4748791,OMIM:618241","Mitochondrial complex I deficiency, nuclear ty...",germline,germline,GRCh37,NC_000011.9,11,126147412,126147412,na,na,11q24.2,"criteria provided, single submitter",2,-,N,"ClinGen:CA113794,UniProtKB:Q96CU9#VAR_064571,O...",3,6,126147412,A,G,-,-,-,-,-,-,SCV005680614,-,-
9,15045,single nucleotide variant,NM_017547.4(FOXRED1):c.1289A>G (p.Asn430Ser),55572,FOXRED1,HGNC:26927,Likely pathogenic,1,"Jun 06, 2024",267606830,-,RCV000000016,"MONDO:MONDO:0032624,MedGen:C4748791,OMIM:618241","Mitochondrial complex I deficiency, nuclear ty...",germline,germline,GRCh38,NC_000011.10,11,126277517,126277517,na,na,11q24.2,"criteria provided, single submitter",2,-,N,"ClinGen:CA113794,UniProtKB:Q96CU9#VAR_064571,O...",3,6,126277517,A,G,-,-,-,-,-,-,SCV005680614,-,-
10,15046,single nucleotide variant,NM_025152.3(NUBPL):c.166G>A (p.Gly56Arg),80224,NUBPL,HGNC:20278,Conflicting classifications of pathogenicity,1,"Apr 08, 2025",200401432,-,RCV000196589|RCV000622708|RCV001526454|RCV0050...,"MedGen:C3661900|MeSH:D030342,MedGen:C0950123|M...",not provided|Inborn genetic diseases|Mitochond...,germline;maternal;paternal,germline,GRCh37,NC_000014.8,14,32031331,32031331,na,na,14q12,"criteria provided, conflicting classifications",6,-,N,"ClinVar:7,UniProtKB:Q8TB37#VAR_064570,OMIM:613...",2,214885,32031331,G,A,-,-,-,-,-,-,SCV000251971|SCV000742093|SCV001736868|SCV0032...,-,-
11,15046,single nucleotide variant,NM_025152.3(NUBPL):c.166G>A (p.Gly56Arg),80224,NUBPL,HGNC:20278,Conflicting classifications of pathogenicity,1,"Apr 08, 2025",200401432,-,RCV000196589|RCV000622708|RCV001526454|RCV0050...,"MedGen:C3661900|MeSH:D030342,MedGen:C0950123|M...",not provided|Inborn genetic diseases|Mitochond...,germline;maternal;paternal,germline,GRCh38,NC_000014.9,14,31562125,31562125,na,na,14q12,"criteria provided, conflicting classifications",6,-,N,"ClinVar:7,UniProtKB:Q8TB37#VAR_064570,OMIM:613...",2,214885,31562125,G,A,-,-,-,-,-,-,SCV000251971|SCV000742093|SCV001736868|SCV0032...,-,-
12,15048,single nucleotide variant,NM_000410.4(HFE):c.845G>A (p.Cys282Tyr),3077,HFE,HGNC:4886,"Pathogenic/Pathogenic, low penetrance; risk fa...",1,"Jun 01, 2026",1800562,-,RCV000000019|RCV000178096|RCV000210820|RCV0003...,"MONDO:MONDO:0021001,MedGen:C3469186,OMIM:23520...",Hemochromatosis type 1|not provided|Hereditary...,biparental;germline;unknown,germline,GRCh37,NC_000006.11,6,26093141,26093141,na,na,6p22.2,"criteria provided, multiple submitters, no con...",58,"ACMG2021,ACMG2022",Y,"UniProtKB:Q30201#VAR_004398,OMIM:613609.0001,C...",3,9,26093141,G,A,-,-,-,-,-,-,SCV000151394|SCV000206975|SCV000219175|SCV0002...,-,-
13,15048,single nucleotide variant,NM_000410.4(HFE):c.845G>A (p.Cys282Tyr),3077,HFE,HGNC:4886,"Pathogenic/Pathogenic, low penetrance; risk fa...",1,"Jun 01, 2026",1800562,-,RCV000000019|RCV000178096|RCV000210820|RCV0003...,"MONDO:MONDO:0021001,MedGen:C3469186,OMIM:23520...",Hemochromatosis type 1|not provided|Hereditary...,biparental;germline;unknown,germline,GRCh38,NC_000006.12,6,26092913,26092913,na,na,6p22.2,"criteria provided, multiple submitters, no con...",58,"ACMG2021,ACMG2022",Y,"UniProtKB:Q30201#VAR_004398,OMIM:613609.0001,C...",3,9,26092913,G,A,-,-,-,-,-,-,SCV000151394|SCV000206975|SCV000219175|SCV0002...,-,-
14,15049,single nucleotide variant,NM_000410.4(HFE):c.187C>G (p.His63Asp),3077,HFE,HGNC:4886,Conflicting classifications of pathogenicity; ...,1,"Apr 27, 2026",1799945,-,RCV000000026|RCV000175607|RCV000394716|RCV0009...,"MONDO:MONDO:0021001,MedGen:C3469186,OMIM:23520...",Hemochromatosis type 1|not provided|Hereditary...,biparental;germline;inherited;unknown,germline,GRCh37,NC_000006.11,6,26091179,26091179,na,na,6p22.2,"criteria provided, conflicting classifications",60,"ACMG2021,ACMG2022",Y,"UniProtKB:Q30201#VAR_004396,OMIM:613609.0002,C...",3,10,26091179,C,G,-,-,-,-,-,-,SCV000219176|SCV000223933|SCV000227124|SCV0004...,-,-
15,15049,single nucleotide variant,NM_000410.4(HFE):c.187C>G (p.His63Asp),3077,HFE,HGNC:4886,Conflicting classifications of pathogenicity; ...,1,"Apr 27, 2026",1799945,-,RCV000000026|RCV000175607|RCV000394716|RCV0009...,"MONDO:MONDO:0021001,MedGen:C3469186,OMIM:23520...",Hemochromatosis type 1|not provided|Hereditary...,biparental;germline;inherited;unknown,germline,GRCh38,NC_000006.12,6,26090951,26090951,na,na,6p22.2,"criteria provided, conflicting classifications",60,"ACMG2021,ACMG2022",Y,"UniProtKB:Q30201#VAR_004396,OMIM:613609.0002,C...",3,10,26090951,C,G,-,-,-,-,-,-,SCV000219176|SCV000223933|SCV000227124|SCV0004...,-,-
16,15050,single nucleotide variant,NM_000410.4(HFE):c.193A>T (p.Ser65Cys),3077,HFE,HGNC:4886,Conflicting classifications of pathogenicity,1,"Jun 01, 2026",1800730,-,RCV000000028|RCV000290779|RCV000764641|RCV0009...,"MONDO:MONDO:0021001,MedGen:C3469186,OMIM:23520...",Hemochromatosis type 1|Hereditary hemochromato...,germline;unknown,germline,GRCh37,NC_000006.11,6,26091185,26091185,na,na,6p22.2,"criteria provided, conflicting classifications",17,"ACMG2021,ACMG2022",Y,"ClinGen:CA339778,UniProtKB:Q30201#VAR_004397,O...",3,11,26091185,A,T,-,-,-,-,-,-,SCV000254532|SCV000895749|SCV001154675|SCV0015...,-,-
17,15050,single nucleotide variant,NM_000410.4(HFE):c.193A>T (p.Ser65Cys),3077,HFE,HGNC:4886,Conflicting classifications of pathogenicity,1,"Jun 01, 2026",1800730,-,RCV000000028|RCV000290779|RCV000764641|RCV0009...,"MONDO:MONDO:0021001,MedGen:C3469186,OMIM:23520...",Hemochromatosis type 1|Hereditary hemochromato...,germline;unknown,germline,GRCh38,NC_000006.12,6,26090957,26090957,na,na,6p22.2,"criteria provided, conflicting classifications",17,"ACMG2021,ACMG2022",Y,"ClinGen:CA339778,UniProtKB:Q30201#VAR_004397,O...",3,11,26090957,A,T,-,-,-,-,-,-,SCV000254532|SCV000895749|SCV001154675|SCV0015...,-,-
18,15051,single nucleotide variant,NM_000410.4(HFE):c.314T>C (p.Ile105Thr),3077,HFE,HGNC:4886,Uncertain significance,1,"Aug 25, 2021",28934596,-,RCV000000029|RCV001322296,"MONDO:MONDO:0021001,MedGen:C3469186,OMIM:23520...",Hemochromatosis type 1|Hereditary hemochromatosis,germline,germline,GRCh37,NC_000006.11,6,26091306,26091306,na,na,6p22.2,"criteria provided, single submitter",2,"ACMG2021,ACMG2022",N,"ClinGen:CA280941,UniProtKB:Q30201#VAR_008730,O...",3,12,26091306,T,C,-,-,-,-,-,-,SCV001513159,-,-
19,15051,single nucleotide variant,NM_000410.4(HFE):c.314T>C (p.Ile105Thr),3077,HFE,HGNC:4886,Uncertain significance,1,"Aug 25, 2021",28934596,-,RCV000000029|RCV001322296,"MONDO:MONDO:0021001,MedGen:C3469186,OMIM:23520...",Hemochromatosis type 1|Hereditary hemochromatosis,germline,germline,GRCh38,NC_000006.12,6,26091078,26091078,na,na,6p22.2,"criteria provided, single submitter",2,"ACMG2021,ACMG2022",N,"ClinGen:CA280941,UniProtKB:Q30201#VAR_008730,O...",3,12,26091078,T,C,-,-,-,-,-,-,SCV001513159,-,-

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9048962 entries, 0 to 9048961
Data columns (total 43 columns):
 #   Column                                      Dtype
---  ------                                      -----
 0   #AlleleID                                   int64
 1   Type                                        str
 2   Name                                        str
 3   GeneID                                      int64
 4   GeneSymbol                                  str
 5   HGNC_ID                                     str
 6   ClinicalSignificance                        str
 7   ClinSigSimple                               int64
 8   LastEvaluated                               str
 9   RS# (dbSNP)                                 int64
 10  nsv/esv (dbVar)                             str
 11  RCVaccession                                str
 12  PhenotypeIDS                                str
 13  PhenotypeList                               str
 14  Origin                                      str
 15  OriginSimple                                str
 16  Assembly                                    str
 17  ChromosomeAccession                         str
 18  Chromosome                                  object
 19  Start                                       int64
 20  Stop                                        int64
 21  ReferenceAllele                             str
 22  AlternateAllele                             str
 23  Cytogenetic                                 str
 24  ReviewStatus                                str
 25  NumberSubmitters                            int64
 26  Guidelines                                  str
 27  TestedInGTR                                 str
 28  OtherIDs                                    str
 29  SubmitterCategories                         int64
 30  VariationID                                 int64
 31  PositionVCF                                 int64
 32  ReferenceAlleleVCF                          str
 33  AlternateAlleleVCF                          str
 34  SomaticClinicalImpact                       str
 35  SomaticClinicalImpactLastEvaluated          str
 36  ReviewStatusClinicalImpact                  str
 37  Oncogenicity                                str
 38  OncogenicityLastEvaluated                   str
 39  ReviewStatusOncogenicity                    str
 40  SCVsForAggregateGermlineClassification      str
 41  SCVsForAggregateSomaticClinicalImpact       str
 42  SCVsForAggregateOncogenicityClassification  str
dtypes: int64(10), object(1), str(32)
memory usage: 5.8+ GB

In [5]:
df[df == "-"].count()

#AlleleID                                           0
Type                                                0
Name                                                0
GeneID                                              0
GeneSymbol                                       9815
HGNC_ID                                         66572
ClinicalSignificance                           490808
ClinSigSimple                                       0
LastEvaluated                                  566488
RS# (dbSNP)                                         0
nsv/esv (dbVar)                               9013111
RCVaccession                                     1403
PhenotypeIDS                                   144733
PhenotypeList                                    1599
Origin                                              0
OriginSimple                                        0
Assembly                                            0
ChromosomeAccession                                 0
Chromosome                                          0
Start                                               0
Stop                                                0
ReferenceAllele                                    70
AlternateAllele                                   556
Cytogenetic                                     18054
ReviewStatus                                   490808
NumberSubmitters                                    0
Guidelines                                    8371588
TestedInGTR                                         0
OtherIDs                                      3240848
SubmitterCategories                                 0
VariationID                                         0
PositionVCF                                         0
ReferenceAlleleVCF                                  0
AlternateAlleleVCF                                  0
SomaticClinicalImpact                         9044929
SomaticClinicalImpactLastEvaluated            9046601
ReviewStatusClinicalImpact                    9044929
Oncogenicity                                  9043759
OncogenicityLastEvaluated                     9045234
ReviewStatusOncogenicity                      9043759
SCVsForAggregateGermlineClassification         492211
SCVsForAggregateSomaticClinicalImpact         9046332
SCVsForAggregateOncogenicityClassification    9045162
dtype: int64

Column Specifics

In [6]:
df["ReferenceAllele"].unique()

<ArrowStringArray>
[                         'na',                         'CTG',
                'CGCGGGGCGGGG',                           'T',
                       'ATTCT',                           '-',
                      'GGCCTG',                          'AT',
 'GGAAAGCATCTCTGGCTCACCATGTAA',                           'G',
           'GAGTTACAATTTCGATG',                          'CC',
                           'C',                         'GAG',
                         'TGA',                         'CAG',
                           'A',                         'GGC',
                         'TTG']
Length: 19, dtype: str

In [7]:
df["ReferenceAllele"].nunique()

19

In [8]:
for col in df.columns:
    print(col + "\t" + str(df[col].nunique()))

#AlleleID	4558681
Type	15
Name	4551669
GeneID	20274
GeneSymbol	41131
HGNC_ID	19990
ClinicalSignificance	108
ClinSigSimple	3
LastEvaluated	6817
RS# (dbSNP)	2645486
nsv/esv (dbVar)	21825
RCVaccession	4557958
PhenotypeIDS	207331
PhenotypeList	228019
Origin	181
OriginSimple	6
Assembly	4
ChromosomeAccession	141
Chromosome	49
Start	7717733
Stop	7717164
ReferenceAllele	19
AlternateAllele	29
Cytogenetic	3873
ReviewStatus	10
NumberSubmitters	78
Guidelines	6
TestedInGTR	2
OtherIDs	2908511
SubmitterCategories	4
VariationID	4558681
PositionVCF	7645692
ReferenceAlleleVCF	39790
AlternateAlleleVCF	21385
SomaticClinicalImpact	6
SomaticClinicalImpactLastEvaluated	543
ReviewStatusClinicalImpact	5
Oncogenicity	8
OncogenicityLastEvaluated	22
ReviewStatusOncogenicity	6
SCVsForAggregateGermlineClassification	4313673
SCVsForAggregateSomaticClinicalImpact	1317
SCVsForAggregateOncogenicityClassification	1906

In [9]:
df.shape

(9048962, 43)

In [10]:
df["Assembly"].unique()

<ArrowStringArray>
['GRCh37', 'GRCh38', 'na', 'NCBI36']
Length: 4, dtype: str

In [11]:
m = df["Assembly"].value_counts()
print(m)
print(type(m))

Assembly
GRCh37    4544016
GRCh38    4490695
na           9480
NCBI36       4771
Name: count, dtype: int64
<class 'pandas.Series'>

In [12]:
df.groupby("#AlleleID")["Assembly"].nunique() >= 3

#AlleleID
15041      False
15042      False
15043      False
15044      False
15045      False
           ...
4997584    False
4997585    False
4997586    False
4997587    False
4997588    False
Name: Assembly, Length: 4558681, dtype: bool

In [13]:
df.groupby("#AlleleID")["Assembly"].unique()

#AlleleID
15041      [GRCh37, GRCh38]
15042      [GRCh37, GRCh38]
15043      [GRCh37, GRCh38]
15044      [GRCh37, GRCh38]
15045      [GRCh37, GRCh38]
                 ...
4997584            [GRCh38]
4997585            [GRCh38]
4997586    [GRCh37, GRCh38]
4997587            [GRCh37]
4997588            [GRCh37]
Name: Assembly, Length: 4558681, dtype: object

In [14]:
count = df.groupby("#AlleleID")["Assembly"].nunique()

count[count >= 2]

#AlleleID
15041      2
15042      2
15043      2
15044      2
15045      2
          ..
4997577    2
4997579    2
4997580    2
4997581    2
4997586    2
Name: Assembly, Length: 4485495, dtype: int64

In [15]:
df[df["ReferenceAllele"] != "na"][["ReferenceAllele", "AlternateAllele"]].value_counts()

ReferenceAllele              AlternateAllele
-                            na                 53
G                            A                   9
CAG                          na                  6
C                            T                   5
-                            T                   4
                             G                   3
                             A                   3
                             C                   3
T                            C                   3
CTG                          na                  2
CGCGGGGCGGGG                 na                  2
T                            C(2_7)              2
ATTCT                        na                  2
GGCCTG                       na                  2
T                            C(n)                2
AT                           na                  2
C                            G                   2
GGC                          na                  2
-                            Alu                 1
GGAAAGCATCTCTGGCTCACCATGTAA  -                   1
-                            TC                  1
                             CTTA                1
                             ACC                 1
GAGTTACAATTTCGATG            TCT                 1
CC                           G                   1
GAG                          ATA                 1
TGA                          -                   1
C                            -                   1
T                            G                   1
A                            C                   1
                             G                   1
                             -                   1
TTG                          -                   1
Name: count, dtype: int64

In [16]:
df[df["ReferenceAllele"] == "na"]["ReferenceAllele"].count()

np.int64(9048840)

In [17]:
# <class 'pandas.DataFrame'>
# RangeIndex: 9048962 entries, 0 to 9048961
# Data columns (total 43 columns):
#  #   Column                                      Dtype 
# ---  ------                                      ----- 
#  0   #AlleleID                                   int64 
#  1   Type                                        str   
#  2   Name                                        str   
#  3   GeneID                                      int64 
#  4   GeneSymbol                                  str   
#  5   HGNC_ID                                     str   
#  6   ClinicalSignificance                        str   
#  7   ClinSigSimple                               int64 
#  8   LastEvaluated                               str   
#  9   RS# (dbSNP)                                 int64 
#  10  nsv/esv (dbVar)                             str   
#  11  RCVaccession                                str   
#  12  PhenotypeIDS                                str   
#  13  PhenotypeList                               str   
#  14  Origin                                      str   
#  15  OriginSimple                                str   
#  16  Assembly                                    str   
#  17  ChromosomeAccession                         str   
#  18  Chromosome                                  object
#  19  Start                                       int64 
#  20  Stop                                        int64 
#  21  ReferenceAllele                             str   
#  22  AlternateAllele                             str   
#  23  Cytogenetic                                 str   
#  24  ReviewStatus                                str   
#  25  NumberSubmitters                            int64 
#  26  Guidelines                                  str   
#  27  TestedInGTR                                 str   
#  28  OtherIDs                                    str   
#  29  SubmitterCategories                         int64 
#  30  VariationID                                 int64 
#  31  PositionVCF                                 int64 
#  32  ReferenceAlleleVCF                          str   
#  33  AlternateAlleleVCF                          str   
#  34  SomaticClinicalImpact                       str   
#  35  SomaticClinicalImpactLastEvaluated          str   
#  36  ReviewStatusClinicalImpact                  str   
#  37  Oncogenicity                                str   
#  38  OncogenicityLastEvaluated                   str   
#  39  ReviewStatusOncogenicity                    str   
#  40  SCVsForAggregateGermlineClassification      str   
#  41  SCVsForAggregateSomaticClinicalImpact       str   
#  42  SCVsForAggregateOncogenicityClassification  str   


df["SomaticClinicalImpact"].value_counts()

SomaticClinicalImpact
-                                           9044929
Tier I - Strong                                1505
no classification for the single variant       1403
Tier II - Potential                             854
Tier III - Unknown                              190
Tier IV - Benign/Likely benign                   81
Name: count, dtype: int64

In [18]:
df["SomaticClinicalImpactLastEvaluated"].value_counts()

SomaticClinicalImpactLastEvaluated
-               9046601
Oct 10, 2024         46
Oct 14, 2025         24
May 19, 2025         20
May 02, 2026         18
                 ...
Oct 21, 2025          2
Nov 30, 2025          2
May 15, 2026          2
Feb 28, 2026          2
Jun 08, 2026          2
Name: count, Length: 543, dtype: int64

In [19]:
df["ReviewStatusClinicalImpact"].value_counts()

ReviewStatusClinicalImpact
-                                           9044929
criteria provided, single submitter            2422
no classification for the single variant       1403
no assertion criteria provided                  190
criteria provided, multiple submitters           18
Name: count, dtype: int64

In [20]:
df["Oncogenicity"].value_counts()

Oncogenicity
-                                              9043759
Likely oncogenic                                  1972
no classification for the single variant          1403
Uncertain significance                            1018
Oncogenic                                          788
Likely benign                                       10
Benign                                               8
Conflicting classifications of oncogenicity          4
Name: count, dtype: int64

In [21]:
df["ReviewStatusOncogenicity"].value_counts()

ReviewStatusOncogenicity
-                                                       9043759
criteria provided, single submitter                        3544
no classification for the single variant                   1403
no assertion criteria provided                              244
criteria provided, multiple submitters, no conflicts          8
criteria provided, conflicting classifications                4
Name: count, dtype: int64

In [22]:
df["SCVsForAggregateGermlineClassification"].value_counts()

SCVsForAggregateGermlineClassification
-                                                                                                          492211
SCV000053124|SCV000703124|SCV001832261|SCV002519734|SCV002562543|SCV002771823|SCV005198236|SCV007597711         4
SCV000030774                                                                                                    4
SCV000030777                                                                                                    4
SCV005881466                                                                                                    4
                                                                                                            ...
SCV007666075                                                                                                    1
SCV007669883                                                                                                    1
SCV007669884                                                                                                    1
SCV007669885                                                                                                    1
SCV007669886                                                                                                    1
Name: count, Length: 4313673, dtype: int64

In [23]:
df["SCVsForAggregateSomaticClinicalImpact"].value_counts()

SCVsForAggregateSomaticClinicalImpact
-               9046332
SCV007104928          2
SCV007104906          2
SCV007104371          2
SCV007104365          2
                 ...
SCV007615622          2
SCV007615623          2
SCV007655975          2
SCV005061371          1
SCV005687767          1
Name: count, Length: 1317, dtype: int64

In [24]:
df["SCVsForAggregateOncogenicityClassification"].value_counts()

SCVsForAggregateOncogenicityClassification
-               9045162
SCV005093976          2
SCV007129937          2
SCV005094482          2
SCV005871982          2
                 ...
SCV005438029          1
SCV005438010          1
SCV005442829          1
SCV007669889          1
SCV007669890          1
Name: count, Length: 1906, dtype: int64

Changes

In [25]:
df.loc[df["Oncogenicity"] == "-", "Oncogenicity"] = pd.NA

In [26]:
df.loc[df["ReviewStatusOncogenicity"] == "-", "ReviewStatusOncogenicity"] = pd.NA
df.loc[df["SomaticClinicalImpact"] == "-", "SomaticClinicalImpact"] = pd.NA

In [27]:
df.loc[df["SCVsForAggregateOncogenicityClassification"] == "-", "SCVsForAggregateOncogenicityClassification"] = pd.NA

df.loc[df["SCVsForAggregateSomaticClinicalImpact"] == "-", "SCVsForAggregateSomaticClinicalImpact"] = pd.NA

df.loc[df["SCVsForAggregateGermlineClassification"] == "-", "SCVsForAggregateGermlineClassification"] = pd.NA

In [28]:
df.loc[df["ReviewStatusClinicalImpact"] == "-", "ReviewStatusClinicalImpact"] = pd.NA

In [29]:
df[df == "-"].count()

#AlleleID                                           0
Type                                                0
Name                                                0
GeneID                                              0
GeneSymbol                                       9815
HGNC_ID                                         66572
ClinicalSignificance                           490808
ClinSigSimple                                       0
LastEvaluated                                  566488
RS# (dbSNP)                                         0
nsv/esv (dbVar)                               9013111
RCVaccession                                     1403
PhenotypeIDS                                   144733
PhenotypeList                                    1599
Origin                                              0
OriginSimple                                        0
Assembly                                            0
ChromosomeAccession                                 0
Chromosome                                          0
Start                                               0
Stop                                                0
ReferenceAllele                                    70
AlternateAllele                                   556
Cytogenetic                                     18054
ReviewStatus                                   490808
NumberSubmitters                                    0
Guidelines                                    8371588
TestedInGTR                                         0
OtherIDs                                      3240848
SubmitterCategories                                 0
VariationID                                         0
PositionVCF                                         0
ReferenceAlleleVCF                                  0
AlternateAlleleVCF                                  0
SomaticClinicalImpact                               0
SomaticClinicalImpactLastEvaluated            9046601
ReviewStatusClinicalImpact                          0
Oncogenicity                                        0
OncogenicityLastEvaluated                     9045234
ReviewStatusOncogenicity                            0
SCVsForAggregateGermlineClassification              0
SCVsForAggregateSomaticClinicalImpact               0
SCVsForAggregateOncogenicityClassification          0
dtype: int64

In [30]:
df["GeneID"].value_counts()

GeneID
 7273         79767
-1            65525
 675          43618
 472          39197
 4763         34672
              ...
 10281            1
 1617             1
 400736           1
 100505724        1
 100033413        1
Name: count, Length: 20274, dtype: int64

In [31]:
df["GeneSymbol"].value_counts()

GeneSymbol
TTN                                                  79767
BRCA2                                                43618
ATM                                                  39197
NF1                                                  34672
APC                                                  34116
                                                     ...
subset of 224 genes: CDC42BPB:DICER1:IRF2BPL:MEG3        1
subset of 13 genes: SIX3                                 1
subset of 26 genes: CACNA1C                              1
subset of 209 genes: ELANE:STK11                         1
subset of 33 genes: SYNGAP1                              1
Name: count, Length: 41131, dtype: int64

In [32]:
df["HGNC_ID"].value_counts()

HGNC_ID
HGNC:12403    79767
-             66572
HGNC:1101     43618
HGNC:795      39197
HGNC:7765     34672
              ...
HGNC:3045         1
HGNC:2682         1
HGNC:13262        1
HGNC:18915        1
HGNC:33067        1
Name: count, Length: 19990, dtype: int64

In [33]:
df["GeneID"].value_counts()
df["GeneSymbol"].value_counts()
df["HGNC_ID"].value_counts()
df["ClinicalSignificance"].value_counts()

ClinicalSignificance
Uncertain significance                                  4708440
Likely benign                                           2194614
-                                                        490808
Benign                                                   426161
Pathogenic                                               407404
                                                         ...
Likely pathogenic; protective                                 2
Benign; Affects; association; other                           2
Pathogenic/Likely pathogenic/Established risk allele          2
confers sensitivity; other                                    2
Established risk allele; association                          2
Name: count, Length: 108, dtype: int64

In [34]:
df["LastEvaluated"].value_counts()

LastEvaluated
-               566488
Jan 13, 2018     70892
Jan 12, 2018     44236
Feb 01, 2026     27070
Feb 04, 2026     26388
                 ...
Feb 04, 2000         1
Jul 30, 1999         1
Jul 14, 2006         1
Nov 20, 2007         1
Oct 21, 2004         1
Name: count, Length: 6817, dtype: int64

In [35]:
df["nsv/esv (dbVar)"].value_counts()

nsv/esv (dbVar)
-            9013111
nsv529506          8
nsv531743          8
nsv916242          8
nsv932069          7
              ...
4681747            1
6112749            1
3875826            1
3917296            1
3893768            1
Name: count, Length: 21825, dtype: int64

In [36]:
for col in df.columns:
    print("_____________________________" + col.upper() + "_____________________________")
    print(df[col].value_counts())

_____________________________#ALLELEID_____________________________
#AlleleID
24911      4
24912      4
24914      4
24915      4
24916      4
          ..
4997583    1
4997584    1
4997585    1
4997587    1
4997588    1
Name: count, Length: 4558681, dtype: int64
_____________________________TYPE_____________________________
Type
single nucleotide variant    8332011
Deletion                      351882
Duplication                   151080
Microsatellite                 78272
Indel                          38818
copy number gain               32659
copy number loss               30481
Insertion                      28920
Inversion                       3148
Variation                       1131
Translocation                    358
Complex                          103
protein only                      93
fusion                             5
Tandem duplication                 1
Name: count, dtype: int64
_____________________________NAME_____________________________
Name
Single allele                                         6320
GRCh37/hg19 2q13(chr2:110871508-110980919)x1            48
GRCh38/hg38 10q11.22(chr10:46157935-47923579)x3         41
GRCh37/hg19 16p12.2(chr16:21597346-21741439)x1          28
GRCh38/hg38 7q11.1-11.21(chr7:61006478-62410831)x1      18
                                                      ...
GRCh38/hg38 16q24.3(chr16:89185680-89372115)x1           1
GRCh38/hg38 16q24.3(chr16:89331546-89428572)x1           1
GRCh38/hg38 16q24.3(chr16:89487341-89510024)x1           1
GRCh37/hg19 6p21.32(chr6:32634911-33424338)x1            1
GRCh37/hg19 16p13.3(chr16:2147416-2164675)x1             1
Name: count, Length: 4551669, dtype: int64
_____________________________GENEID_____________________________
GeneID
 7273         79767
-1            65525
 675          43618
 472          39197
 4763         34672
              ...
 10281            1
 1617             1
 400736           1
 100505724        1
 100033413        1
Name: count, Length: 20274, dtype: int64
_____________________________GENESYMBOL_____________________________
GeneSymbol
TTN                                                  79767
BRCA2                                                43618
ATM                                                  39197
NF1                                                  34672
APC                                                  34116
                                                     ...
subset of 224 genes: CDC42BPB:DICER1:IRF2BPL:MEG3        1
subset of 13 genes: SIX3                                 1
subset of 26 genes: CACNA1C                              1
subset of 209 genes: ELANE:STK11                         1
subset of 33 genes: SYNGAP1                              1
Name: count, Length: 41131, dtype: int64
_____________________________HGNC_ID_____________________________
HGNC_ID
HGNC:12403    79767
-             66572
HGNC:1101     43618
HGNC:795      39197
HGNC:7765     34672
              ...
HGNC:3045         1
HGNC:2682         1
HGNC:13262        1
HGNC:18915        1
HGNC:33067        1
Name: count, Length: 19990, dtype: int64
_____________________________CLINICALSIGNIFICANCE_____________________________
ClinicalSignificance
Uncertain significance                                  4708440
Likely benign                                           2194614
-                                                        490808
Benign                                                   426161
Pathogenic                                               407404
                                                         ...
Likely pathogenic; protective                                 2
Benign; Affects; association; other                           2
Pathogenic/Likely pathogenic/Established risk allele          2
confers sensitivity; other                                    2
Established risk allele; association                          2
Name: count, Length: 108, dtype: int64
_____________________________CLINSIGSIMPLE_____________________________
ClinSigSimple
 0    7752335
 1     804416
-1     492211
Name: count, dtype: int64
_____________________________LASTEVALUATED_____________________________
LastEvaluated
-               566488
Jan 13, 2018     70892
Jan 12, 2018     44236
Feb 01, 2026     27070
Feb 04, 2026     26388
                 ...
Feb 04, 2000         1
Jul 30, 1999         1
Jul 14, 2006         1
Nov 20, 2007         1
Oct 21, 2004         1
Name: count, Length: 6817, dtype: int64
_____________________________RS# (DBSNP)_____________________________
RS# (dbSNP)
-1             3255083
 56986587           88
 11309117           82
 193922936          80
 746054139          70
                ...
 76237212            1
 1464458411          1
 1798375728          1
 2493718324          1
 782765047           1
Name: count, Length: 2645486, dtype: int64
_____________________________NSV/ESV (DBVAR)_____________________________
nsv/esv (dbVar)
-            9013111
nsv529506          8
nsv531743          8
nsv916242          8
nsv932069          7
              ...
4681747            1
6112749            1
3875826            1
3917296            1
3893768            1
Name: count, Length: 21825, dtype: int64
_____________________________RCVACCESSION_____________________________
RCVaccession
-                                                      1403
RCV000010547|RCV000596801|RCV002247313|RCV004757100       4
RCV000010548                                              4
RCV000010551                                              4
RCV000010552                                              4
                                                       ...
RCV006751629                                              1
RCV006751630                                              1
RCV006751631                                              1
RCV006751633                                              1
RCV006751634                                              1
Name: count, Length: 4557958, dtype: int64
_____________________________PHENOTYPEIDS_____________________________
PhenotypeIDS
MedGen:CN169374                                                     2224240
MedGen:C3661900                                                     1856147
MeSH:D030342,MedGen:C0950123                                         425238
-                                                                    144733
MONDO:MONDO:0015356,MeSH:D009386,MedGen:C0027672,Orphanet:140162     119904
                                                                     ...
MedGen:C5984728                                                           1
MedGen:C0265458                                                           1
MONDO:MONDO:0015583,MedGen:C4304537,Orphanet:163693                       1
MONDO:MONDO:0017229,MedGen:C4749581,Orphanet:280325                       1
MONDO:MONDO:0980973,MedGen:CN380859,OMIM:621495                           1
Name: count, Length: 207331, dtype: int64
_____________________________PHENOTYPELIST_____________________________
PhenotypeList
not specified                              2224240
not provided                               1885277
Inborn genetic diseases                     425238
Hereditary cancer-predisposing syndrome     119904
Thyroid cancer, nonmedullary, 1              77453
                                            ...
Loss of Chromosome Xq                            1
14q partial distal trisomy syndrome              1
2p21 microdeletion syndrome                      1
Distal monosomy 12p                              1
STAD syndrome                                    1
Name: count, Length: 228019, dtype: int64
_____________________________ORIGIN_____________________________
Origin
germline                                  7918259
not applicable                             489088
germline;unknown                           312639
unknown                                    142751
germline;not applicable                     48600
                                           ...
biparental;not applicable;unknown               2
de novo;not applicable;somatic;unknown          2
inherited;maternal;not applicable               2
biparental;de novo;maternal;paternal            2
inherited;not applicable;paternal               1
Name: count, Length: 181, dtype: int64
_____________________________ORIGINSIMPLE_____________________________
OriginSimple
germline            8388406
not applicable       489088
unknown              143499
somatic               13754
not provided           7570
germline/somatic       6645
Name: count, dtype: int64
_____________________________ASSEMBLY_____________________________
Assembly
GRCh37    4544016
GRCh38    4490695
na           9480
NCBI36       4771
Name: count, dtype: int64
_____________________________CHROMOSOMEACCESSION_____________________________
ChromosomeAccession
NC_000001.10    408325
NC_000001.11    404469
NC_000002.11    395828
NC_000002.12    391526
NC_000017.10    274033
                 ...
NT_187499.1          1
NT_113891.2          1
NT_167248.1          1
NT_113891.3          1
NT_167248.2          1
Name: count, Length: 141, dtype: int64
_____________________________CHROMOSOME_____________________________
Chromosome
1     802399
2     733398
17    525387
19    506634
11    481412
3     461506
16    445774
7     408828
5     395786
X     392980
12    384079
6     375204
9     369774
10    311597
4     298250
15    297560
8     278897
14    265238
22    195114
20    192604
13    164069
18    147795
21    100330
2      54266
11     44435
5      41390
3      32097
7      31582
9      30388
6      30092
12     29493
8      27122
10     26598
4      23755
14     21255
16     20731
17     20222
15     16322
13     14813
1      10660
na      9480
19      8209
Y       7054
MT      6264
18      2952
20      2342
22      1682
21      1114
Un        29
Name: count, dtype: int64
_____________________________START_____________________________
Start
-1           9480
 46273462     182
 45770204     182
 203861       138
 22149        118
             ...
 89487341       1
 72873331       1
 72580990       1
 32634911       1
 2147416        1
Name: count, Length: 7717733, dtype: int64
_____________________________STOP_____________________________
Stop
-1            9482
 46273463      184
 45770205      184
 155233731      85
 78014123       81
              ...
 89510024        1
 72873331        1
 72580990        1
 33424338        1
 2164675         1
Name: count, Length: 7717164, dtype: int64
_____________________________REFERENCEALLELE_____________________________
ReferenceAllele
na                             9048840
-                                   70
G                                    9
T                                    8
C                                    8
CAG                                  6
A                                    3
CTG                                  2
CGCGGGGCGGGG                         2
ATTCT                                2
GGCCTG                               2
AT                                   2
GGC                                  2
GGAAAGCATCTCTGGCTCACCATGTAA          1
GAGTTACAATTTCGATG                    1
CC                                   1
GAG                                  1
TGA                                  1
TTG                                  1
Name: count, dtype: int64
_____________________________ALTERNATEALLELE_____________________________
AlternateAllele
na                      9048325
-                           556
A                            12
G                            11
T                             9
C                             7
CA                            4
TC                            3
GG                            2
ATAAATCACTTAGAGATGT           2
CTA                           2
C(2_7)                        2
AATTAAGGTATA                  2
TCCCGGGTTCAAGCGATTCT          2
C(n)                          2
TTTCCGACAAAGGT                2
CACAAAGTG                     2
AC                            2
TGACATCAGTCCGGGCAC            2
TTGAA                         2
GTGG                          2
AGTTACC                       2
Alu                           1
CTTA                          1
ACC                           1
TCT                           1
ATA                           1
TG                            1
TGG                           1
Name: count, dtype: int64
_____________________________CYTOGENETIC_____________________________
Cytogenetic
16p13.3         135975
2q31.2           86378
19p13.2          79579
19p13.3          77126
19q13.2          71355
                 ...
12q12-14.3           1
3q25.33-29           1
7q21.12-36.3         1
7q31.2-32.2          1
7q32.2-36.3          1
Name: count, Length: 3873, dtype: int64
_____________________________REVIEWSTATUS_____________________________
ReviewStatus
criteria provided, single submitter                     6558623
criteria provided, multiple submitters, no conflicts    1338730
-                                                        490808
criteria provided, conflicting classifications           331022
no assertion criteria provided                           268542
reviewed by expert panel                                  44627
no classification provided                                14803
no classification for the single variant                   1403
no classifications from unflagged records                   288
practice guideline                                          116
Name: count, dtype: int64
_____________________________NUMBERSUBMITTERS_____________________________
NumberSubmitters
1     7169699
2     1077473
3      362387
4      164908
5       90384
       ...
90          2
70          2
73          2
69          2
87          2
Name: count, Length: 78, dtype: int64
_____________________________GUIDELINES_____________________________
Guidelines
-                                      8371588
ACMG2013,ACMG2016,ACMG2021,ACMG2022     502717
ACMG2021,ACMG2022                       136472
ACMG2016,ACMG2021,ACMG2022               20513
ACMG2022                                 12077
ACMG2013                                  5595
Name: count, dtype: int64
_____________________________TESTEDINGTR_____________________________
TestedInGTR
N    9047746
Y       1216
Name: count, dtype: int64
_____________________________OTHERIDS_____________________________
OtherIDs
-                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               3240848
ClinVar:1723892                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      86
OMIM:154270.0001,ClinVar:14353                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       16
OMIM:111700.0002,ClinVar:17709                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        8
ClinVar:633844,ClinVar:633885,ClinVar:633887,ClinVar:633888,ClinVar:633904,ClinVar:633905,ClinVar:633910,ClinVar:633913,ClinVar:633916,ClinVar:633925,ClinVar:633927,ClinVar:633930,ClinVar:633941,ClinVar:633952,ClinVar:633958,ClinVar:633965,ClinVar:634060,ClinVar:634114,ClinVar:634132,ClinVar:634136,ClinVar:634137,ClinVar:634138,ClinVar:634205,ClinVar:634212,ClinVar:634213,ClinVar:634232,ClinVar:634272,ClinVar:634298,ClinVar:634355,ClinVar:634365,ClinVar:634375,ClinVar:634413,ClinVar:634414,ClinVar:634427,ClinVar:638789          8
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ...
OMIM:614804.0001                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      1
OMIM:607559.0001                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      1
OMIM:120140.0059                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      1
OMIM:602661.0011                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      1

In [37]:
df.loc[df["LastEvaluated"] == "-", "LastEvaluated"] = pd.NA

df.loc[df["SomaticClinicalImpactLastEvaluated"] == "-", "SomaticClinicalImpactLastEvaluated"] = pd.NA

df.loc[df["OncogenicityLastEvaluated"] == "-", "OncogenicityLastEvaluated"] = pd.NA

df.loc[df["Start"] == "-", "Start"] = pd.NA

In [38]:
df.loc[df["OtherIDs"] == "-", "OtherIDs"] = pd.NA


df.loc[df["ReferenceAlleleVCF"] == "na", "ReferenceAlleleVCF"] = pd.NA
df.loc[df["ReferenceAlleleVCF"] == "", "ReferenceAlleleVCF"] = pd.NA

df.loc[df["AlternateAlleleVCF"] == "na", "AlternateAlleleVCF"] = pd.NA
df.loc[df["AlternateAlleleVCF"] == "", "AlternateAlleleVCF"] = pd.NA

In [39]:
df["Chromosome"].map(type).value_counts()

Chromosome
<class 'str'>    8557442
<class 'int'>     491520
Name: count, dtype: int64

In [40]:
# LEAVE ClinSigSimple ALONE - DO NOT EDIT
# ClinSigSimple is a simplified representation of clinical significance, where the values generally encode:

# 0 → No clinical significance / benign
# 1 → Clinical significance present / pathogenic
# -1 → Not classified / uncertain / conflicting or unable to assign a simple significance



df.loc[df["HGNC_ID"] == "-", "HGNC_ID"] = pd.NA
df.loc[df["ClinicalSignificance"] == "-", "ClinicalSignificance"] = pd.NA


# NOTE: Convert LastEvaluated to datetime


df.loc[df["RCVaccession"] == "-", "RCVaccession"] = pd.NA
df.loc[df["PhenotypeIDS"] == "-", "PhenotypeIDS"] = pd.NA

In [41]:
# CONVERT TO DATETIME HERE

# First turn - into NULL
df.loc[df["LastEvaluated"] == "-", "LastEvaluated"] = pd.NA

df.loc[df["SomaticClinicalImpactLastEvaluated"] == "-", "SomaticClinicalImpactLastEvaluated"] = pd.NA

df.loc[df["OncogenicityLastEvaluated"] == "-", "OncogenicityLastEvaluated"] = pd.NA

In [42]:
# CONVERT TO DATETIME HERE

# Convert to datetime
df["LastEvaluated"] = pd.to_datetime(df["LastEvaluated"], format="%b %d, %Y")

df["SomaticClinicalImpactLastEvaluated"] = pd.to_datetime(df["SomaticClinicalImpactLastEvaluated"], format="%b %d, %Y")

df["OncogenicityLastEvaluated"] = pd.to_datetime(df["OncogenicityLastEvaluated"], format="%b %d, %Y")

In [43]:
df["LastEvaluated"].value_counts()

LastEvaluated
2018-01-13    70892
2018-01-12    44236
2026-02-01    27070
2026-02-04    26388
2026-01-26    21970
              ...
2000-02-04        1
1999-07-30        1
2006-07-14        1
2007-11-20        1
2004-10-21        1
Name: count, Length: 6816, dtype: int64

In [44]:
df["SomaticClinicalImpactLastEvaluated"].value_counts()

SomaticClinicalImpactLastEvaluated
2024-10-10    46
2025-10-14    24
2025-05-19    20
2026-05-02    18
2022-11-07    16
              ..
2025-10-21     2
2025-11-30     2
2026-05-15     2
2026-02-28     2
2026-06-08     2
Name: count, Length: 542, dtype: int64

In [45]:
df["OncogenicityLastEvaluated"].value_counts()

OncogenicityLastEvaluated
2025-03-04    2172
2025-12-29    1252
2024-11-13      92
2025-03-30      90
2019-05-21      26
2025-10-12      22
2024-11-22      13
2025-05-22       8
2026-08-17       6
2016-07-11       6
2025-02-20       6
2023-07-01       6
2019-07-19       5
2024-01-24       4
2025-05-20       4
2023-05-10       4
2024-06-24       4
2020-06-30       2
2016-04-12       2
2025-01-10       2
2024-11-05       2
Name: count, dtype: int64

In [46]:
for col in df.columns:
    print("_____________________________" + col.upper() + "_____________________________")
    print(df[col].value_counts())

_____________________________#ALLELEID_____________________________
#AlleleID
24911      4
24912      4
24914      4
24915      4
24916      4
          ..
4997583    1
4997584    1
4997585    1
4997587    1
4997588    1
Name: count, Length: 4558681, dtype: int64
_____________________________TYPE_____________________________
Type
single nucleotide variant    8332011
Deletion                      351882
Duplication                   151080
Microsatellite                 78272
Indel                          38818
copy number gain               32659
copy number loss               30481
Insertion                      28920
Inversion                       3148
Variation                       1131
Translocation                    358
Complex                          103
protein only                      93
fusion                             5
Tandem duplication                 1
Name: count, dtype: int64
_____________________________NAME_____________________________
Name
Single allele                                         6320
GRCh37/hg19 2q13(chr2:110871508-110980919)x1            48
GRCh38/hg38 10q11.22(chr10:46157935-47923579)x3         41
GRCh37/hg19 16p12.2(chr16:21597346-21741439)x1          28
GRCh38/hg38 7q11.1-11.21(chr7:61006478-62410831)x1      18
                                                      ...
GRCh38/hg38 16q24.3(chr16:89185680-89372115)x1           1
GRCh38/hg38 16q24.3(chr16:89331546-89428572)x1           1
GRCh38/hg38 16q24.3(chr16:89487341-89510024)x1           1
GRCh37/hg19 6p21.32(chr6:32634911-33424338)x1            1
GRCh37/hg19 16p13.3(chr16:2147416-2164675)x1             1
Name: count, Length: 4551669, dtype: int64
_____________________________GENEID_____________________________
GeneID
 7273         79767
-1            65525
 675          43618
 472          39197
 4763         34672
              ...
 10281            1
 1617             1
 400736           1
 100505724        1
 100033413        1
Name: count, Length: 20274, dtype: int64
_____________________________GENESYMBOL_____________________________
GeneSymbol
TTN                                                  79767
BRCA2                                                43618
ATM                                                  39197
NF1                                                  34672
APC                                                  34116
                                                     ...
subset of 224 genes: CDC42BPB:DICER1:IRF2BPL:MEG3        1
subset of 13 genes: SIX3                                 1
subset of 26 genes: CACNA1C                              1
subset of 209 genes: ELANE:STK11                         1
subset of 33 genes: SYNGAP1                              1
Name: count, Length: 41131, dtype: int64
_____________________________HGNC_ID_____________________________
HGNC_ID
HGNC:12403    79767
HGNC:1101     43618
HGNC:795      39197
HGNC:7765     34672
HGNC:583      34116
              ...
HGNC:3045         1
HGNC:2682         1
HGNC:13262        1
HGNC:18915        1
HGNC:33067        1
Name: count, Length: 19989, dtype: int64
_____________________________CLINICALSIGNIFICANCE_____________________________
ClinicalSignificance
Uncertain significance                                  4708440
Likely benign                                           2194614
Benign                                                   426161
Pathogenic                                               407404
Conflicting classifications of pathogenicity             331775
                                                         ...
Likely pathogenic; protective                                 2
Benign; Affects; association; other                           2
Pathogenic/Likely pathogenic/Established risk allele          2
confers sensitivity; other                                    2
Established risk allele; association                          2
Name: count, Length: 107, dtype: int64
_____________________________CLINSIGSIMPLE_____________________________
ClinSigSimple
 0    7752335
 1     804416
-1     492211
Name: count, dtype: int64
_____________________________LASTEVALUATED_____________________________
LastEvaluated
2018-01-13    70892
2018-01-12    44236
2026-02-01    27070
2026-02-04    26388
2026-01-26    21970
              ...
2000-02-04        1
1999-07-30        1
2006-07-14        1
2007-11-20        1
2004-10-21        1
Name: count, Length: 6816, dtype: int64
_____________________________RS# (DBSNP)_____________________________
RS# (dbSNP)
-1             3255083
 56986587           88
 11309117           82
 193922936          80
 746054139          70
                ...
 76237212            1
 1464458411          1
 1798375728          1
 2493718324          1
 782765047           1
Name: count, Length: 2645486, dtype: int64
_____________________________NSV/ESV (DBVAR)_____________________________
nsv/esv (dbVar)
-            9013111
nsv529506          8
nsv531743          8
nsv916242          8
nsv932069          7
              ...
4681747            1
6112749            1
3875826            1
3917296            1
3893768            1
Name: count, Length: 21825, dtype: int64
_____________________________RCVACCESSION_____________________________
RCVaccession
RCV000010547|RCV000596801|RCV002247313|RCV004757100    4
RCV000010548                                           4
RCV000010551                                           4
RCV000010552                                           4
RCV000010553                                           4
                                                      ..
RCV006751629                                           1
RCV006751630                                           1
RCV006751631                                           1
RCV006751633                                           1
RCV006751634                                           1
Name: count, Length: 4557957, dtype: int64
_____________________________PHENOTYPEIDS_____________________________
PhenotypeIDS
MedGen:CN169374                                                     2224240
MedGen:C3661900                                                     1856147
MeSH:D030342,MedGen:C0950123                                         425238
MONDO:MONDO:0015356,MeSH:D009386,MedGen:C0027672,Orphanet:140162     119904
MONDO:MONDO:0008567,MedGen:C4721429,OMIM:188550                       77453
                                                                     ...
MedGen:C5984728                                                           1
MedGen:C0265458                                                           1
MONDO:MONDO:0015583,MedGen:C4304537,Orphanet:163693                       1
MONDO:MONDO:0017229,MedGen:C4749581,Orphanet:280325                       1
MONDO:MONDO:0980973,MedGen:CN380859,OMIM:621495                           1
Name: count, Length: 207330, dtype: int64
_____________________________PHENOTYPELIST_____________________________
PhenotypeList
not specified                              2224240
not provided                               1885277
Inborn genetic diseases                     425238
Hereditary cancer-predisposing syndrome     119904
Thyroid cancer, nonmedullary, 1              77453
                                            ...
Loss of Chromosome Xq                            1
14q partial distal trisomy syndrome              1
2p21 microdeletion syndrome                      1
Distal monosomy 12p                              1
STAD syndrome                                    1
Name: count, Length: 228019, dtype: int64
_____________________________ORIGIN_____________________________
Origin
germline                                  7918259
not applicable                             489088
germline;unknown                           312639
unknown                                    142751
germline;not applicable                     48600
                                           ...
biparental;not applicable;unknown               2
de novo;not applicable;somatic;unknown          2
inherited;maternal;not applicable               2
biparental;de novo;maternal;paternal            2
inherited;not applicable;paternal               1
Name: count, Length: 181, dtype: int64
_____________________________ORIGINSIMPLE_____________________________
OriginSimple
germline            8388406
not applicable       489088
unknown              143499
somatic               13754
not provided           7570
germline/somatic       6645
Name: count, dtype: int64
_____________________________ASSEMBLY_____________________________
Assembly
GRCh37    4544016
GRCh38    4490695
na           9480
NCBI36       4771
Name: count, dtype: int64
_____________________________CHROMOSOMEACCESSION_____________________________
ChromosomeAccession
NC_000001.10    408325
NC_000001.11    404469
NC_000002.11    395828
NC_000002.12    391526
NC_000017.10    274033
                 ...
NT_187499.1          1
NT_113891.2          1
NT_167248.1          1
NT_113891.3          1
NT_167248.2          1
Name: count, Length: 141, dtype: int64
_____________________________CHROMOSOME_____________________________
Chromosome
1     802399
2     733398
17    525387
19    506634
11    481412
3     461506
16    445774
7     408828
5     395786
X     392980
12    384079
6     375204
9     369774
10    311597
4     298250
15    297560
8     278897
14    265238
22    195114
20    192604
13    164069
18    147795
21    100330
2      54266
11     44435
5      41390
3      32097
7      31582
9      30388
6      30092
12     29493
8      27122
10     26598
4      23755
14     21255
16     20731
17     20222
15     16322
13     14813
1      10660
na      9480
19      8209
Y       7054
MT      6264
18      2952
20      2342
22      1682
21      1114
Un        29
Name: count, dtype: int64
_____________________________START_____________________________
Start
-1.0           9480
 46273462.0     182
 45770204.0     182
 203861.0       138
 22149.0        118
               ...
 89487341.0       1
 72873331.0       1
 72580990.0       1
 32634911.0       1
 2147416.0        1
Name: count, Length: 7717733, dtype: int64
_____________________________STOP_____________________________
Stop
-1            9482
 46273463      184
 45770205      184
 155233731      85
 78014123       81
              ...
 89510024        1
 72873331        1
 72580990        1
 33424338        1
 2164675         1
Name: count, Length: 7717164, dtype: int64
_____________________________REFERENCEALLELE_____________________________
ReferenceAllele
na                             9048840
-                                   70
G                                    9
T                                    8
C                                    8
CAG                                  6
A                                    3
CTG                                  2
CGCGGGGCGGGG                         2
ATTCT                                2
GGCCTG                               2
AT                                   2
GGC                                  2
GGAAAGCATCTCTGGCTCACCATGTAA          1
GAGTTACAATTTCGATG                    1
CC                                   1
GAG                                  1
TGA                                  1
TTG                                  1
Name: count, dtype: int64
_____________________________ALTERNATEALLELE_____________________________
AlternateAllele
na                      9048325
-                           556
A                            12
G                            11
T                             9
C                             7
CA                            4
TC                            3
GG                            2
ATAAATCACTTAGAGATGT           2
CTA                           2
C(2_7)                        2
AATTAAGGTATA                  2
TCCCGGGTTCAAGCGATTCT          2
C(n)                          2
TTTCCGACAAAGGT                2
CACAAAGTG                     2
AC                            2
TGACATCAGTCCGGGCAC            2
TTGAA                         2
GTGG                          2
AGTTACC                       2
Alu                           1
CTTA                          1
ACC                           1
TCT                           1
ATA                           1
TG                            1
TGG                           1
Name: count, dtype: int64
_____________________________CYTOGENETIC_____________________________
Cytogenetic
16p13.3         135975
2q31.2           86378
19p13.2          79579
19p13.3          77126
19q13.2          71355
                 ...
12q12-14.3           1
3q25.33-29           1
7q21.12-36.3         1
7q31.2-32.2          1
7q32.2-36.3          1
Name: count, Length: 3873, dtype: int64
_____________________________REVIEWSTATUS_____________________________
ReviewStatus
criteria provided, single submitter                     6558623
criteria provided, multiple submitters, no conflicts    1338730
-                                                        490808
criteria provided, conflicting classifications           331022
no assertion criteria provided                           268542
reviewed by expert panel                                  44627
no classification provided                                14803
no classification for the single variant                   1403
no classifications from unflagged records                   288
practice guideline                                          116
Name: count, dtype: int64
_____________________________NUMBERSUBMITTERS_____________________________
NumberSubmitters
1     7169699
2     1077473
3      362387
4      164908
5       90384
       ...
90          2
70          2
73          2
69          2
87          2
Name: count, Length: 78, dtype: int64
_____________________________GUIDELINES_____________________________
Guidelines
-                                      8371588
ACMG2013,ACMG2016,ACMG2021,ACMG2022     502717
ACMG2021,ACMG2022                       136472
ACMG2016,ACMG2021,ACMG2022               20513
ACMG2022                                 12077
ACMG2013                                  5595
Name: count, dtype: int64
_____________________________TESTEDINGTR_____________________________
TestedInGTR
N    9047746
Y       1216
Name: count, dtype: int64
_____________________________OTHERIDS_____________________________
OtherIDs
ClinVar:1723892                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 86
OMIM:154270.0001,ClinVar:14353                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  16
OMIM:111700.0002,ClinVar:17709                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   8
ClinVar:633844,ClinVar:633885,ClinVar:633887,ClinVar:633888,ClinVar:633904,ClinVar:633905,ClinVar:633910,ClinVar:633913,ClinVar:633916,ClinVar:633925,ClinVar:633927,ClinVar:633930,ClinVar:633941,ClinVar:633952,ClinVar:633958,ClinVar:633965,ClinVar:634060,ClinVar:634114,ClinVar:634132,ClinVar:634136,ClinVar:634137,ClinVar:634138,ClinVar:634205,ClinVar:634212,ClinVar:634213,ClinVar:634232,ClinVar:634272,ClinVar:634298,ClinVar:634355,ClinVar:634365,ClinVar:634375,ClinVar:634413,ClinVar:634414,ClinVar:634427,ClinVar:638789     8
ClinVar:869112                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   8
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ..
OMIM:614804.0001                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 1
OMIM:607559.0001                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 1
OMIM:120140.0059                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 1
OMIM:602661.0011                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 1

In [47]:
df.loc[df["nsv/esv (dbVar)"] == "-", "nsv/esv (dbVar)"] = pd.NA

In [48]:

df.loc[df["Start"] == -1, "Start"] = pd.NA
df.loc[df["Stop"] == -1, "Stop"] = pd.NA


df.loc[df["RS# (dbSNP)"] == -1, "RS# (dbSNP)"] = pd.NA

df.loc[df["PositionVCF"] == -1, "PositionVCF"] = pd.NA

In [49]:
for col in df.columns:
    print("_____________________________" + col.upper() + "_____________________________")
    print(df[col].value_counts())

_____________________________#ALLELEID_____________________________
#AlleleID
24911      4
24912      4
24914      4
24915      4
24916      4
          ..
4997583    1
4997584    1
4997585    1
4997587    1
4997588    1
Name: count, Length: 4558681, dtype: int64
_____________________________TYPE_____________________________
Type
single nucleotide variant    8332011
Deletion                      351882
Duplication                   151080
Microsatellite                 78272
Indel                          38818
copy number gain               32659
copy number loss               30481
Insertion                      28920
Inversion                       3148
Variation                       1131
Translocation                    358
Complex                          103
protein only                      93
fusion                             5
Tandem duplication                 1
Name: count, dtype: int64
_____________________________NAME_____________________________
Name
Single allele                                         6320
GRCh37/hg19 2q13(chr2:110871508-110980919)x1            48
GRCh38/hg38 10q11.22(chr10:46157935-47923579)x3         41
GRCh37/hg19 16p12.2(chr16:21597346-21741439)x1          28
GRCh38/hg38 7q11.1-11.21(chr7:61006478-62410831)x1      18
                                                      ...
GRCh38/hg38 16q24.3(chr16:89185680-89372115)x1           1
GRCh38/hg38 16q24.3(chr16:89331546-89428572)x1           1
GRCh38/hg38 16q24.3(chr16:89487341-89510024)x1           1
GRCh37/hg19 6p21.32(chr6:32634911-33424338)x1            1
GRCh37/hg19 16p13.3(chr16:2147416-2164675)x1             1
Name: count, Length: 4551669, dtype: int64
_____________________________GENEID_____________________________
GeneID
 7273         79767
-1            65525
 675          43618
 472          39197
 4763         34672
              ...
 10281            1
 1617             1
 400736           1
 100505724        1
 100033413        1
Name: count, Length: 20274, dtype: int64
_____________________________GENESYMBOL_____________________________
GeneSymbol
TTN                                                  79767
BRCA2                                                43618
ATM                                                  39197
NF1                                                  34672
APC                                                  34116
                                                     ...
subset of 224 genes: CDC42BPB:DICER1:IRF2BPL:MEG3        1
subset of 13 genes: SIX3                                 1
subset of 26 genes: CACNA1C                              1
subset of 209 genes: ELANE:STK11                         1
subset of 33 genes: SYNGAP1                              1
Name: count, Length: 41131, dtype: int64
_____________________________HGNC_ID_____________________________
HGNC_ID
HGNC:12403    79767
HGNC:1101     43618
HGNC:795      39197
HGNC:7765     34672
HGNC:583      34116
              ...
HGNC:3045         1
HGNC:2682         1
HGNC:13262        1
HGNC:18915        1
HGNC:33067        1
Name: count, Length: 19989, dtype: int64
_____________________________CLINICALSIGNIFICANCE_____________________________
ClinicalSignificance
Uncertain significance                                  4708440
Likely benign                                           2194614
Benign                                                   426161
Pathogenic                                               407404
Conflicting classifications of pathogenicity             331775
                                                         ...
Likely pathogenic; protective                                 2
Benign; Affects; association; other                           2
Pathogenic/Likely pathogenic/Established risk allele          2
confers sensitivity; other                                    2
Established risk allele; association                          2
Name: count, Length: 107, dtype: int64
_____________________________CLINSIGSIMPLE_____________________________
ClinSigSimple
 0    7752335
 1     804416
-1     492211
Name: count, dtype: int64
_____________________________LASTEVALUATED_____________________________
LastEvaluated
2018-01-13    70892
2018-01-12    44236
2026-02-01    27070
2026-02-04    26388
2026-01-26    21970
              ...
2000-02-04        1
1999-07-30        1
2006-07-14        1
2007-11-20        1
2004-10-21        1
Name: count, Length: 6816, dtype: int64
_____________________________RS# (DBSNP)_____________________________
RS# (dbSNP)
5.698659e+07    88
1.130912e+07    82
1.939229e+08    80
7.460541e+08    70
3.078066e+06    60
                ..
7.623721e+07     1
1.464458e+09     1
1.798376e+09     1
2.493718e+09     1
7.827650e+08     1
Name: count, Length: 2645485, dtype: int64
_____________________________NSV/ESV (DBVAR)_____________________________
nsv/esv (dbVar)
nsv529506    8
nsv531743    8
nsv916242    8
nsv932069    7
nsv491969    6
            ..
4681747      1
6112749      1
3875826      1
3917296      1
3893768      1
Name: count, Length: 21824, dtype: int64
_____________________________RCVACCESSION_____________________________
RCVaccession
RCV000010547|RCV000596801|RCV002247313|RCV004757100    4
RCV000010548                                           4
RCV000010551                                           4
RCV000010552                                           4
RCV000010553                                           4
                                                      ..
RCV006751629                                           1
RCV006751630                                           1
RCV006751631                                           1
RCV006751633                                           1
RCV006751634                                           1
Name: count, Length: 4557957, dtype: int64
_____________________________PHENOTYPEIDS_____________________________
PhenotypeIDS
MedGen:CN169374                                                     2224240
MedGen:C3661900                                                     1856147
MeSH:D030342,MedGen:C0950123                                         425238
MONDO:MONDO:0015356,MeSH:D009386,MedGen:C0027672,Orphanet:140162     119904
MONDO:MONDO:0008567,MedGen:C4721429,OMIM:188550                       77453
                                                                     ...
MedGen:C5984728                                                           1
MedGen:C0265458                                                           1
MONDO:MONDO:0015583,MedGen:C4304537,Orphanet:163693                       1
MONDO:MONDO:0017229,MedGen:C4749581,Orphanet:280325                       1
MONDO:MONDO:0980973,MedGen:CN380859,OMIM:621495                           1
Name: count, Length: 207330, dtype: int64
_____________________________PHENOTYPELIST_____________________________
PhenotypeList
not specified                              2224240
not provided                               1885277
Inborn genetic diseases                     425238
Hereditary cancer-predisposing syndrome     119904
Thyroid cancer, nonmedullary, 1              77453
                                            ...
Loss of Chromosome Xq                            1
14q partial distal trisomy syndrome              1
2p21 microdeletion syndrome                      1
Distal monosomy 12p                              1
STAD syndrome                                    1
Name: count, Length: 228019, dtype: int64
_____________________________ORIGIN_____________________________
Origin
germline                                  7918259
not applicable                             489088
germline;unknown                           312639
unknown                                    142751
germline;not applicable                     48600
                                           ...
biparental;not applicable;unknown               2
de novo;not applicable;somatic;unknown          2
inherited;maternal;not applicable               2
biparental;de novo;maternal;paternal            2
inherited;not applicable;paternal               1
Name: count, Length: 181, dtype: int64
_____________________________ORIGINSIMPLE_____________________________
OriginSimple
germline            8388406
not applicable       489088
unknown              143499
somatic               13754
not provided           7570
germline/somatic       6645
Name: count, dtype: int64
_____________________________ASSEMBLY_____________________________
Assembly
GRCh37    4544016
GRCh38    4490695
na           9480
NCBI36       4771
Name: count, dtype: int64
_____________________________CHROMOSOMEACCESSION_____________________________
ChromosomeAccession
NC_000001.10    408325
NC_000001.11    404469
NC_000002.11    395828
NC_000002.12    391526
NC_000017.10    274033
                 ...
NT_187499.1          1
NT_113891.2          1
NT_167248.1          1
NT_113891.3          1
NT_167248.2          1
Name: count, Length: 141, dtype: int64
_____________________________CHROMOSOME_____________________________
Chromosome
1     802399
2     733398
17    525387
19    506634
11    481412
3     461506
16    445774
7     408828
5     395786
X     392980
12    384079
6     375204
9     369774
10    311597
4     298250
15    297560
8     278897
14    265238
22    195114
20    192604
13    164069
18    147795
21    100330
2      54266
11     44435
5      41390
3      32097
7      31582
9      30388
6      30092
12     29493
8      27122
10     26598
4      23755
14     21255
16     20731
17     20222
15     16322
13     14813
1      10660
na      9480
19      8209
Y       7054
MT      6264
18      2952
20      2342
22      1682
21      1114
Un        29
Name: count, dtype: int64
_____________________________START_____________________________
Start
46273462.0    182
45770204.0    182
203861.0      138
22149.0       118
18339130.0     91
             ...
89487341.0      1
72873331.0      1
72580990.0      1
32634911.0      1
2147416.0       1
Name: count, Length: 7717732, dtype: int64
_____________________________STOP_____________________________
Stop
46273463.0     184
45770205.0     184
155233731.0     85
78014123.0      81
115107733.0     70
              ...
89510024.0       1
72873331.0       1
72580990.0       1
33424338.0       1
2164675.0        1
Name: count, Length: 7717163, dtype: int64
_____________________________REFERENCEALLELE_____________________________
ReferenceAllele
na                             9048840
-                                   70
G                                    9
T                                    8
C                                    8
CAG                                  6
A                                    3
CTG                                  2
CGCGGGGCGGGG                         2
ATTCT                                2
GGCCTG                               2
AT                                   2
GGC                                  2
GGAAAGCATCTCTGGCTCACCATGTAA          1
GAGTTACAATTTCGATG                    1
CC                                   1
GAG                                  1
TGA                                  1
TTG                                  1
Name: count, dtype: int64
_____________________________ALTERNATEALLELE_____________________________
AlternateAllele
na                      9048325
-                           556
A                            12
G                            11
T                             9
C                             7
CA                            4
TC                            3
GG                            2
ATAAATCACTTAGAGATGT           2
CTA                           2
C(2_7)                        2
AATTAAGGTATA                  2
TCCCGGGTTCAAGCGATTCT          2
C(n)                          2
TTTCCGACAAAGGT                2
CACAAAGTG                     2
AC                            2
TGACATCAGTCCGGGCAC            2
TTGAA                         2
GTGG                          2
AGTTACC                       2
Alu                           1
CTTA                          1
ACC                           1
TCT                           1
ATA                           1
TG                            1
TGG                           1
Name: count, dtype: int64
_____________________________CYTOGENETIC_____________________________
Cytogenetic
16p13.3         135975
2q31.2           86378
19p13.2          79579
19p13.3          77126
19q13.2          71355
                 ...
12q12-14.3           1
3q25.33-29           1
7q21.12-36.3         1
7q31.2-32.2          1
7q32.2-36.3          1
Name: count, Length: 3873, dtype: int64
_____________________________REVIEWSTATUS_____________________________
ReviewStatus
criteria provided, single submitter                     6558623
criteria provided, multiple submitters, no conflicts    1338730
-                                                        490808
criteria provided, conflicting classifications           331022
no assertion criteria provided                           268542
reviewed by expert panel                                  44627
no classification provided                                14803
no classification for the single variant                   1403
no classifications from unflagged records                   288
practice guideline                                          116
Name: count, dtype: int64
_____________________________NUMBERSUBMITTERS_____________________________
NumberSubmitters
1     7169699
2     1077473
3      362387
4      164908
5       90384
       ...
90          2
70          2
73          2
69          2
87          2
Name: count, Length: 78, dtype: int64
_____________________________GUIDELINES_____________________________
Guidelines
-                                      8371588
ACMG2013,ACMG2016,ACMG2021,ACMG2022     502717
ACMG2021,ACMG2022                       136472
ACMG2016,ACMG2021,ACMG2022               20513
ACMG2022                                 12077
ACMG2013                                  5595
Name: count, dtype: int64
_____________________________TESTEDINGTR_____________________________
TestedInGTR
N    9047746
Y       1216
Name: count, dtype: int64
_____________________________OTHERIDS_____________________________
OtherIDs
ClinVar:1723892                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 86
OMIM:154270.0001,ClinVar:14353                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  16
OMIM:111700.0002,ClinVar:17709                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   8
ClinVar:633844,ClinVar:633885,ClinVar:633887,ClinVar:633888,ClinVar:633904,ClinVar:633905,ClinVar:633910,ClinVar:633913,ClinVar:633916,ClinVar:633925,ClinVar:633927,ClinVar:633930,ClinVar:633941,ClinVar:633952,ClinVar:633958,ClinVar:633965,ClinVar:634060,ClinVar:634114,ClinVar:634132,ClinVar:634136,ClinVar:634137,ClinVar:634138,ClinVar:634205,ClinVar:634212,ClinVar:634213,ClinVar:634232,ClinVar:634272,ClinVar:634298,ClinVar:634355,ClinVar:634365,ClinVar:634375,ClinVar:634413,ClinVar:634414,ClinVar:634427,ClinVar:638789     8
ClinVar:869112                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   8
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ..
OMIM:614804.0001                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 1
OMIM:607559.0001                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 1
OMIM:120140.0059                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 1
OMIM:602661.0011                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 1

In [50]:
df.loc[df["GeneID"] == -1, "GeneID"] = pd.NA

In [51]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9048962 entries, 0 to 9048961
Data columns (total 43 columns):
 #   Column                                      Dtype
---  ------                                      -----
 0   #AlleleID                                   int64
 1   Type                                        str
 2   Name                                        str
 3   GeneID                                      float64
 4   GeneSymbol                                  str
 5   HGNC_ID                                     str
 6   ClinicalSignificance                        str
 7   ClinSigSimple                               int64
 8   LastEvaluated                               datetime64[us]
 9   RS# (dbSNP)                                 float64
 10  nsv/esv (dbVar)                             str
 11  RCVaccession                                str
 12  PhenotypeIDS                                str
 13  PhenotypeList                               str
 14  Origin                                      str
 15  OriginSimple                                str
 16  Assembly                                    str
 17  ChromosomeAccession                         str
 18  Chromosome                                  object
 19  Start                                       float64
 20  Stop                                        float64
 21  ReferenceAllele                             str
 22  AlternateAllele                             str
 23  Cytogenetic                                 str
 24  ReviewStatus                                str
 25  NumberSubmitters                            int64
 26  Guidelines                                  str
 27  TestedInGTR                                 str
 28  OtherIDs                                    str
 29  SubmitterCategories                         int64
 30  VariationID                                 int64
 31  PositionVCF                                 float64
 32  ReferenceAlleleVCF                          str
 33  AlternateAlleleVCF                          str
 34  SomaticClinicalImpact                       str
 35  SomaticClinicalImpactLastEvaluated          datetime64[us]
 36  ReviewStatusClinicalImpact                  str
 37  Oncogenicity                                str
 38  OncogenicityLastEvaluated                   datetime64[us]
 39  ReviewStatusOncogenicity                    str
 40  SCVsForAggregateGermlineClassification      str
 41  SCVsForAggregateSomaticClinicalImpact       str
 42  SCVsForAggregateOncogenicityClassification  str
dtypes: datetime64[us](3), float64(5), int64(5), object(1), str(29)
memory usage: 5.6+ GB

In [52]:
# CONVERT TO INT: GeneID, Start, Stop, PositionVCF

df["GeneID"] = df["GeneID"].astype("Int64")
df["Start"] = df["Start"].astype("Int64")
df["Stop"] = df["Stop"].astype("Int64")
df["PositionVCF"] = df["PositionVCF"].astype("Int64")

In [53]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9048962 entries, 0 to 9048961
Data columns (total 43 columns):
 #   Column                                      Dtype
---  ------                                      -----
 0   #AlleleID                                   int64
 1   Type                                        str
 2   Name                                        str
 3   GeneID                                      Int64
 4   GeneSymbol                                  str
 5   HGNC_ID                                     str
 6   ClinicalSignificance                        str
 7   ClinSigSimple                               int64
 8   LastEvaluated                               datetime64[us]
 9   RS# (dbSNP)                                 float64
 10  nsv/esv (dbVar)                             str
 11  RCVaccession                                str
 12  PhenotypeIDS                                str
 13  PhenotypeList                               str
 14  Origin                                      str
 15  OriginSimple                                str
 16  Assembly                                    str
 17  ChromosomeAccession                         str
 18  Chromosome                                  object
 19  Start                                       Int64
 20  Stop                                        Int64
 21  ReferenceAllele                             str
 22  AlternateAllele                             str
 23  Cytogenetic                                 str
 24  ReviewStatus                                str
 25  NumberSubmitters                            int64
 26  Guidelines                                  str
 27  TestedInGTR                                 str
 28  OtherIDs                                    str
 29  SubmitterCategories                         int64
 30  VariationID                                 int64
 31  PositionVCF                                 Int64
 32  ReferenceAlleleVCF                          str
 33  AlternateAlleleVCF                          str
 34  SomaticClinicalImpact                       str
 35  SomaticClinicalImpactLastEvaluated          datetime64[us]
 36  ReviewStatusClinicalImpact                  str
 37  Oncogenicity                                str
 38  OncogenicityLastEvaluated                   datetime64[us]
 39  ReviewStatusOncogenicity                    str
 40  SCVsForAggregateGermlineClassification      str
 41  SCVsForAggregateSomaticClinicalImpact       str
 42  SCVsForAggregateOncogenicityClassification  str
dtypes: Int64(4), datetime64[us](3), float64(1), int64(5), object(1), str(29)
memory usage: 5.6+ GB

In [54]:
df[df == "-"].count()

#AlleleID                                           0
Type                                                0
Name                                                0
GeneID                                              0
GeneSymbol                                       9815
HGNC_ID                                             0
ClinicalSignificance                                0
ClinSigSimple                                       0
LastEvaluated                                       0
RS# (dbSNP)                                         0
nsv/esv (dbVar)                                     0
RCVaccession                                        0
PhenotypeIDS                                        0
PhenotypeList                                    1599
Origin                                              0
OriginSimple                                        0
Assembly                                            0
ChromosomeAccession                                 0
Chromosome                                          0
Start                                               0
Stop                                                0
ReferenceAllele                                    70
AlternateAllele                                   556
Cytogenetic                                     18054
ReviewStatus                                   490808
NumberSubmitters                                    0
Guidelines                                    8371588
TestedInGTR                                         0
OtherIDs                                            0
SubmitterCategories                                 0
VariationID                                         0
PositionVCF                                         0
ReferenceAlleleVCF                                  0
AlternateAlleleVCF                                  0
SomaticClinicalImpact                               0
SomaticClinicalImpactLastEvaluated                  0
ReviewStatusClinicalImpact                          0
Oncogenicity                                        0
OncogenicityLastEvaluated                           0
ReviewStatusOncogenicity                            0
SCVsForAggregateGermlineClassification              0
SCVsForAggregateSomaticClinicalImpact               0
SCVsForAggregateOncogenicityClassification          0
dtype: int64

In [55]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9048962 entries, 0 to 9048961
Data columns (total 43 columns):
 #   Column                                      Dtype
---  ------                                      -----
 0   #AlleleID                                   int64
 1   Type                                        str
 2   Name                                        str
 3   GeneID                                      Int64
 4   GeneSymbol                                  str
 5   HGNC_ID                                     str
 6   ClinicalSignificance                        str
 7   ClinSigSimple                               int64
 8   LastEvaluated                               datetime64[us]
 9   RS# (dbSNP)                                 float64
 10  nsv/esv (dbVar)                             str
 11  RCVaccession                                str
 12  PhenotypeIDS                                str
 13  PhenotypeList                               str
 14  Origin                                      str
 15  OriginSimple                                str
 16  Assembly                                    str
 17  ChromosomeAccession                         str
 18  Chromosome                                  object
 19  Start                                       Int64
 20  Stop                                        Int64
 21  ReferenceAllele                             str
 22  AlternateAllele                             str
 23  Cytogenetic                                 str
 24  ReviewStatus                                str
 25  NumberSubmitters                            int64
 26  Guidelines                                  str
 27  TestedInGTR                                 str
 28  OtherIDs                                    str
 29  SubmitterCategories                         int64
 30  VariationID                                 int64
 31  PositionVCF                                 Int64
 32  ReferenceAlleleVCF                          str
 33  AlternateAlleleVCF                          str
 34  SomaticClinicalImpact                       str
 35  SomaticClinicalImpactLastEvaluated          datetime64[us]
 36  ReviewStatusClinicalImpact                  str
 37  Oncogenicity                                str
 38  OncogenicityLastEvaluated                   datetime64[us]
 39  ReviewStatusOncogenicity                    str
 40  SCVsForAggregateGermlineClassification      str
 41  SCVsForAggregateSomaticClinicalImpact       str
 42  SCVsForAggregateOncogenicityClassification  str
dtypes: Int64(4), datetime64[us](3), float64(1), int64(5), object(1), str(29)
memory usage: 5.6+ GB

In [56]:
df["RS# (dbSNP)"].head(10)

0    397704705.0
1    397704705.0
2    397704709.0
3    397704709.0
4    150829393.0
5    150829393.0
6    267606829.0
7    267606829.0
8    267606830.0
9    267606830.0
Name: RS# (dbSNP), dtype: float64

In [57]:
df["RS# (dbSNP)"].isna().sum()

np.int64(3255083)

In [58]:
df["RS# (dbSNP)"] = df["RS# (dbSNP)"].astype("Int64")

In [59]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9048962 entries, 0 to 9048961
Data columns (total 43 columns):
 #   Column                                      Dtype
---  ------                                      -----
 0   #AlleleID                                   int64
 1   Type                                        str
 2   Name                                        str
 3   GeneID                                      Int64
 4   GeneSymbol                                  str
 5   HGNC_ID                                     str
 6   ClinicalSignificance                        str
 7   ClinSigSimple                               int64
 8   LastEvaluated                               datetime64[us]
 9   RS# (dbSNP)                                 Int64
 10  nsv/esv (dbVar)                             str
 11  RCVaccession                                str
 12  PhenotypeIDS                                str
 13  PhenotypeList                               str
 14  Origin                                      str
 15  OriginSimple                                str
 16  Assembly                                    str
 17  ChromosomeAccession                         str
 18  Chromosome                                  object
 19  Start                                       Int64
 20  Stop                                        Int64
 21  ReferenceAllele                             str
 22  AlternateAllele                             str
 23  Cytogenetic                                 str
 24  ReviewStatus                                str
 25  NumberSubmitters                            int64
 26  Guidelines                                  str
 27  TestedInGTR                                 str
 28  OtherIDs                                    str
 29  SubmitterCategories                         int64
 30  VariationID                                 int64
 31  PositionVCF                                 Int64
 32  ReferenceAlleleVCF                          str
 33  AlternateAlleleVCF                          str
 34  SomaticClinicalImpact                       str
 35  SomaticClinicalImpactLastEvaluated          datetime64[us]
 36  ReviewStatusClinicalImpact                  str
 37  Oncogenicity                                str
 38  OncogenicityLastEvaluated                   datetime64[us]
 39  ReviewStatusOncogenicity                    str
 40  SCVsForAggregateGermlineClassification      str
 41  SCVsForAggregateSomaticClinicalImpact       str
 42  SCVsForAggregateOncogenicityClassification  str
dtypes: Int64(5), datetime64[us](3), int64(5), object(1), str(29)
memory usage: 5.7+ GB

In [60]:
for col in df.columns:
    print("_____________________________" + col.upper() + "_____________________________")
    print(df[col].value_counts())

_____________________________#ALLELEID_____________________________
#AlleleID
24911      4
24912      4
24914      4
24915      4
24916      4
          ..
4997583    1
4997584    1
4997585    1
4997587    1
4997588    1
Name: count, Length: 4558681, dtype: int64
_____________________________TYPE_____________________________
Type
single nucleotide variant    8332011
Deletion                      351882
Duplication                   151080
Microsatellite                 78272
Indel                          38818
copy number gain               32659
copy number loss               30481
Insertion                      28920
Inversion                       3148
Variation                       1131
Translocation                    358
Complex                          103
protein only                      93
fusion                             5
Tandem duplication                 1
Name: count, dtype: int64
_____________________________NAME_____________________________
Name
Single allele                                         6320
GRCh37/hg19 2q13(chr2:110871508-110980919)x1            48
GRCh38/hg38 10q11.22(chr10:46157935-47923579)x3         41
GRCh37/hg19 16p12.2(chr16:21597346-21741439)x1          28
GRCh38/hg38 7q11.1-11.21(chr7:61006478-62410831)x1      18
                                                      ...
GRCh38/hg38 16q24.3(chr16:89185680-89372115)x1           1
GRCh38/hg38 16q24.3(chr16:89331546-89428572)x1           1
GRCh38/hg38 16q24.3(chr16:89487341-89510024)x1           1
GRCh37/hg19 6p21.32(chr6:32634911-33424338)x1            1
GRCh37/hg19 16p13.3(chr16:2147416-2164675)x1             1
Name: count, Length: 4551669, dtype: int64
_____________________________GENEID_____________________________
GeneID
7273         79767
675          43618
472          39197
4763         34672
324          34116
             ...
10281            1
1617             1
400736           1
100505724        1
100033413        1
Name: count, Length: 20273, dtype: Int64
_____________________________GENESYMBOL_____________________________
GeneSymbol
TTN                                                  79767
BRCA2                                                43618
ATM                                                  39197
NF1                                                  34672
APC                                                  34116
                                                     ...
subset of 224 genes: CDC42BPB:DICER1:IRF2BPL:MEG3        1
subset of 13 genes: SIX3                                 1
subset of 26 genes: CACNA1C                              1
subset of 209 genes: ELANE:STK11                         1
subset of 33 genes: SYNGAP1                              1
Name: count, Length: 41131, dtype: int64
_____________________________HGNC_ID_____________________________
HGNC_ID
HGNC:12403    79767
HGNC:1101     43618
HGNC:795      39197
HGNC:7765     34672
HGNC:583      34116
              ...
HGNC:3045         1
HGNC:2682         1
HGNC:13262        1
HGNC:18915        1
HGNC:33067        1
Name: count, Length: 19989, dtype: int64
_____________________________CLINICALSIGNIFICANCE_____________________________
ClinicalSignificance
Uncertain significance                                  4708440
Likely benign                                           2194614
Benign                                                   426161
Pathogenic                                               407404
Conflicting classifications of pathogenicity             331775
                                                         ...
Likely pathogenic; protective                                 2
Benign; Affects; association; other                           2
Pathogenic/Likely pathogenic/Established risk allele          2
confers sensitivity; other                                    2
Established risk allele; association                          2
Name: count, Length: 107, dtype: int64
_____________________________CLINSIGSIMPLE_____________________________
ClinSigSimple
 0    7752335
 1     804416
-1     492211
Name: count, dtype: int64
_____________________________LASTEVALUATED_____________________________
LastEvaluated
2018-01-13    70892
2018-01-12    44236
2026-02-01    27070
2026-02-04    26388
2026-01-26    21970
              ...
2000-02-04        1
1999-07-30        1
2006-07-14        1
2007-11-20        1
2004-10-21        1
Name: count, Length: 6816, dtype: int64
_____________________________RS# (DBSNP)_____________________________
RS# (dbSNP)
56986587      88
11309117      82
193922936     80
746054139     70
3078066       60
              ..
76237212       1
1464458411     1
1798375728     1
2493718324     1
782765047      1
Name: count, Length: 2645485, dtype: Int64
_____________________________NSV/ESV (DBVAR)_____________________________
nsv/esv (dbVar)
nsv529506    8
nsv531743    8
nsv916242    8
nsv932069    7
nsv491969    6
            ..
4681747      1
6112749      1
3875826      1
3917296      1
3893768      1
Name: count, Length: 21824, dtype: int64
_____________________________RCVACCESSION_____________________________
RCVaccession
RCV000010547|RCV000596801|RCV002247313|RCV004757100    4
RCV000010548                                           4
RCV000010551                                           4
RCV000010552                                           4
RCV000010553                                           4
                                                      ..
RCV006751629                                           1
RCV006751630                                           1
RCV006751631                                           1
RCV006751633                                           1
RCV006751634                                           1
Name: count, Length: 4557957, dtype: int64
_____________________________PHENOTYPEIDS_____________________________
PhenotypeIDS
MedGen:CN169374                                                     2224240
MedGen:C3661900                                                     1856147
MeSH:D030342,MedGen:C0950123                                         425238
MONDO:MONDO:0015356,MeSH:D009386,MedGen:C0027672,Orphanet:140162     119904
MONDO:MONDO:0008567,MedGen:C4721429,OMIM:188550                       77453
                                                                     ...
MedGen:C5984728                                                           1
MedGen:C0265458                                                           1
MONDO:MONDO:0015583,MedGen:C4304537,Orphanet:163693                       1
MONDO:MONDO:0017229,MedGen:C4749581,Orphanet:280325                       1
MONDO:MONDO:0980973,MedGen:CN380859,OMIM:621495                           1
Name: count, Length: 207330, dtype: int64
_____________________________PHENOTYPELIST_____________________________
PhenotypeList
not specified                              2224240
not provided                               1885277
Inborn genetic diseases                     425238
Hereditary cancer-predisposing syndrome     119904
Thyroid cancer, nonmedullary, 1              77453
                                            ...
Loss of Chromosome Xq                            1
14q partial distal trisomy syndrome              1
2p21 microdeletion syndrome                      1
Distal monosomy 12p                              1
STAD syndrome                                    1
Name: count, Length: 228019, dtype: int64
_____________________________ORIGIN_____________________________
Origin
germline                                  7918259
not applicable                             489088
germline;unknown                           312639
unknown                                    142751
germline;not applicable                     48600
                                           ...
biparental;not applicable;unknown               2
de novo;not applicable;somatic;unknown          2
inherited;maternal;not applicable               2
biparental;de novo;maternal;paternal            2
inherited;not applicable;paternal               1
Name: count, Length: 181, dtype: int64
_____________________________ORIGINSIMPLE_____________________________
OriginSimple
germline            8388406
not applicable       489088
unknown              143499
somatic               13754
not provided           7570
germline/somatic       6645
Name: count, dtype: int64
_____________________________ASSEMBLY_____________________________
Assembly
GRCh37    4544016
GRCh38    4490695
na           9480
NCBI36       4771
Name: count, dtype: int64
_____________________________CHROMOSOMEACCESSION_____________________________
ChromosomeAccession
NC_000001.10    408325
NC_000001.11    404469
NC_000002.11    395828
NC_000002.12    391526
NC_000017.10    274033
                 ...
NT_187499.1          1
NT_113891.2          1
NT_167248.1          1
NT_113891.3          1
NT_167248.2          1
Name: count, Length: 141, dtype: int64
_____________________________CHROMOSOME_____________________________
Chromosome
1     802399
2     733398
17    525387
19    506634
11    481412
3     461506
16    445774
7     408828
5     395786
X     392980
12    384079
6     375204
9     369774
10    311597
4     298250
15    297560
8     278897
14    265238
22    195114
20    192604
13    164069
18    147795
21    100330
2      54266
11     44435
5      41390
3      32097
7      31582
9      30388
6      30092
12     29493
8      27122
10     26598
4      23755
14     21255
16     20731
17     20222
15     16322
13     14813
1      10660
na      9480
19      8209
Y       7054
MT      6264
18      2952
20      2342
22      1682
21      1114
Un        29
Name: count, dtype: int64
_____________________________START_____________________________
Start
46273462    182
45770204    182
203861      138
22149       118
18339130     91
           ...
89487341      1
72873331      1
72580990      1
32634911      1
2147416       1
Name: count, Length: 7717732, dtype: Int64
_____________________________STOP_____________________________
Stop
46273463     184
45770205     184
155233731     85
78014123      81
115107733     70
            ...
89510024       1
72873331       1
72580990       1
33424338       1
2164675        1
Name: count, Length: 7717163, dtype: Int64
_____________________________REFERENCEALLELE_____________________________
ReferenceAllele
na                             9048840
-                                   70
G                                    9
T                                    8
C                                    8
CAG                                  6
A                                    3
CTG                                  2
CGCGGGGCGGGG                         2
ATTCT                                2
GGCCTG                               2
AT                                   2
GGC                                  2
GGAAAGCATCTCTGGCTCACCATGTAA          1
GAGTTACAATTTCGATG                    1
CC                                   1
GAG                                  1
TGA                                  1
TTG                                  1
Name: count, dtype: int64
_____________________________ALTERNATEALLELE_____________________________
AlternateAllele
na                      9048325
-                           556
A                            12
G                            11
T                             9
C                             7
CA                            4
TC                            3
GG                            2
ATAAATCACTTAGAGATGT           2
CTA                           2
C(2_7)                        2
AATTAAGGTATA                  2
TCCCGGGTTCAAGCGATTCT          2
C(n)                          2
TTTCCGACAAAGGT                2
CACAAAGTG                     2
AC                            2
TGACATCAGTCCGGGCAC            2
TTGAA                         2
GTGG                          2
AGTTACC                       2
Alu                           1
CTTA                          1
ACC                           1
TCT                           1
ATA                           1
TG                            1
TGG                           1
Name: count, dtype: int64
_____________________________CYTOGENETIC_____________________________
Cytogenetic
16p13.3         135975
2q31.2           86378
19p13.2          79579
19p13.3          77126
19q13.2          71355
                 ...
12q12-14.3           1
3q25.33-29           1
7q21.12-36.3         1
7q31.2-32.2          1
7q32.2-36.3          1
Name: count, Length: 3873, dtype: int64
_____________________________REVIEWSTATUS_____________________________
ReviewStatus
criteria provided, single submitter                     6558623
criteria provided, multiple submitters, no conflicts    1338730
-                                                        490808
criteria provided, conflicting classifications           331022
no assertion criteria provided                           268542
reviewed by expert panel                                  44627
no classification provided                                14803
no classification for the single variant                   1403
no classifications from unflagged records                   288
practice guideline                                          116
Name: count, dtype: int64
_____________________________NUMBERSUBMITTERS_____________________________
NumberSubmitters
1     7169699
2     1077473
3      362387
4      164908
5       90384
       ...
90          2
70          2
73          2
69          2
87          2
Name: count, Length: 78, dtype: int64
_____________________________GUIDELINES_____________________________
Guidelines
-                                      8371588
ACMG2013,ACMG2016,ACMG2021,ACMG2022     502717
ACMG2021,ACMG2022                       136472
ACMG2016,ACMG2021,ACMG2022               20513
ACMG2022                                 12077
ACMG2013                                  5595
Name: count, dtype: int64
_____________________________TESTEDINGTR_____________________________
TestedInGTR
N    9047746
Y       1216
Name: count, dtype: int64
_____________________________OTHERIDS_____________________________
OtherIDs
ClinVar:1723892                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 86
OMIM:154270.0001,ClinVar:14353                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  16
OMIM:111700.0002,ClinVar:17709                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   8
ClinVar:633844,ClinVar:633885,ClinVar:633887,ClinVar:633888,ClinVar:633904,ClinVar:633905,ClinVar:633910,ClinVar:633913,ClinVar:633916,ClinVar:633925,ClinVar:633927,ClinVar:633930,ClinVar:633941,ClinVar:633952,ClinVar:633958,ClinVar:633965,ClinVar:634060,ClinVar:634114,ClinVar:634132,ClinVar:634136,ClinVar:634137,ClinVar:634138,ClinVar:634205,ClinVar:634212,ClinVar:634213,ClinVar:634232,ClinVar:634272,ClinVar:634298,ClinVar:634355,ClinVar:634365,ClinVar:634375,ClinVar:634413,ClinVar:634414,ClinVar:634427,ClinVar:638789     8
ClinVar:869112                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   8
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ..
OMIM:614804.0001                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 1
OMIM:607559.0001                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 1
OMIM:120140.0059                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 1
OMIM:602661.0011                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 1

In [61]:
df["Chromosome"] = df["Chromosome"].astype(str)

In [62]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9048962 entries, 0 to 9048961
Data columns (total 43 columns):
 #   Column                                      Dtype
---  ------                                      -----
 0   #AlleleID                                   int64
 1   Type                                        str
 2   Name                                        str
 3   GeneID                                      Int64
 4   GeneSymbol                                  str
 5   HGNC_ID                                     str
 6   ClinicalSignificance                        str
 7   ClinSigSimple                               int64
 8   LastEvaluated                               datetime64[us]
 9   RS# (dbSNP)                                 Int64
 10  nsv/esv (dbVar)                             str
 11  RCVaccession                                str
 12  PhenotypeIDS                                str
 13  PhenotypeList                               str
 14  Origin                                      str
 15  OriginSimple                                str
 16  Assembly                                    str
 17  ChromosomeAccession                         str
 18  Chromosome                                  str
 19  Start                                       Int64
 20  Stop                                        Int64
 21  ReferenceAllele                             str
 22  AlternateAllele                             str
 23  Cytogenetic                                 str
 24  ReviewStatus                                str
 25  NumberSubmitters                            int64
 26  Guidelines                                  str
 27  TestedInGTR                                 str
 28  OtherIDs                                    str
 29  SubmitterCategories                         int64
 30  VariationID                                 int64
 31  PositionVCF                                 Int64
 32  ReferenceAlleleVCF                          str
 33  AlternateAlleleVCF                          str
 34  SomaticClinicalImpact                       str
 35  SomaticClinicalImpactLastEvaluated          datetime64[us]
 36  ReviewStatusClinicalImpact                  str
 37  Oncogenicity                                str
 38  OncogenicityLastEvaluated                   datetime64[us]
 39  ReviewStatusOncogenicity                    str
 40  SCVsForAggregateGermlineClassification      str
 41  SCVsForAggregateSomaticClinicalImpact       str
 42  SCVsForAggregateOncogenicityClassification  str
dtypes: Int64(5), datetime64[us](3), int64(5), str(30)
memory usage: 5.7 GB

In [63]:
df.isna().sum().sort_values(ascending=False)

SomaticClinicalImpactLastEvaluated            9046601
SCVsForAggregateSomaticClinicalImpact         9046332
OncogenicityLastEvaluated                     9045234
SCVsForAggregateOncogenicityClassification    9045162
ReviewStatusClinicalImpact                    9044929
SomaticClinicalImpact                         9044929
ReviewStatusOncogenicity                      9043759
Oncogenicity                                  9043759
nsv/esv (dbVar)                               9013111
RS# (dbSNP)                                   3255083
OtherIDs                                      3240848
LastEvaluated                                  566488
SCVsForAggregateGermlineClassification         492211
ClinicalSignificance                           490808
PhenotypeIDS                                   144733
PositionVCF                                    108251
AlternateAlleleVCF                             108251
ReferenceAlleleVCF                             108251
HGNC_ID                                         66572
GeneID                                          65525
Stop                                             9482
Start                                            9480
RCVaccession                                     1403
#AlleleID                                           0
GeneSymbol                                          0
Type                                                0
Name                                                0
ClinSigSimple                                       0
NumberSubmitters                                    0
ReviewStatus                                        0
Cytogenetic                                         0
Guidelines                                          0
ReferenceAllele                                     0
ChromosomeAccession                                 0
Chromosome                                          0
Origin                                              0
PhenotypeList                                       0
Assembly                                            0
OriginSimple                                        0
AlternateAllele                                     0
SubmitterCategories                                 0
VariationID                                         0
TestedInGTR                                         0
dtype: int64

In [64]:
(df == "-").sum().sort_values(ascending=False)

Guidelines                                    8371588
ReviewStatus                                   490808
Cytogenetic                                     18054
GeneSymbol                                       9815
PhenotypeList                                    1599
AlternateAllele                                   556
ReferenceAllele                                    70
Name                                                0
GeneID                                              0
Type                                                0
#AlleleID                                           0
nsv/esv (dbVar)                                     0
RS# (dbSNP)                                         0
LastEvaluated                                       0
ClinSigSimple                                       0
ClinicalSignificance                                0
HGNC_ID                                             0
PhenotypeIDS                                        0
RCVaccession                                        0
Chromosome                                          0
ChromosomeAccession                                 0
Assembly                                            0
OriginSimple                                        0
Origin                                              0
Stop                                                0
Start                                               0
NumberSubmitters                                    0
TestedInGTR                                         0
OtherIDs                                            0
SubmitterCategories                                 0
VariationID                                         0
PositionVCF                                         0
ReferenceAlleleVCF                                  0
AlternateAlleleVCF                                  0
SomaticClinicalImpact                               0
SomaticClinicalImpactLastEvaluated                  0
ReviewStatusClinicalImpact                          0
Oncogenicity                                        0
OncogenicityLastEvaluated                           0
ReviewStatusOncogenicity                            0
SCVsForAggregateGermlineClassification              0
SCVsForAggregateSomaticClinicalImpact               0
SCVsForAggregateOncogenicityClassification          0
dtype: Int64

In [65]:
df.loc[df["Cytogenetic"] == "-", "Cytogenetic"] = pd.NA

In [66]:
(df == "-").sum().sort_values(ascending=False)

Guidelines                                    8371588
ReviewStatus                                   490808
GeneSymbol                                       9815
PhenotypeList                                    1599
AlternateAllele                                   556
ReferenceAllele                                    70
HGNC_ID                                             0
Name                                                0
GeneID                                              0
Type                                                0
#AlleleID                                           0
nsv/esv (dbVar)                                     0
RS# (dbSNP)                                         0
LastEvaluated                                       0
ClinSigSimple                                       0
ClinicalSignificance                                0
RCVaccession                                        0
PhenotypeIDS                                        0
Origin                                              0
Chromosome                                          0
ChromosomeAccession                                 0
Assembly                                            0
OriginSimple                                        0
Start                                               0
Stop                                                0
Cytogenetic                                         0
NumberSubmitters                                    0
TestedInGTR                                         0
OtherIDs                                            0
SubmitterCategories                                 0
VariationID                                         0
PositionVCF                                         0
ReferenceAlleleVCF                                  0
AlternateAlleleVCF                                  0
SomaticClinicalImpact                               0
SomaticClinicalImpactLastEvaluated                  0
ReviewStatusClinicalImpact                          0
Oncogenicity                                        0
OncogenicityLastEvaluated                           0
ReviewStatusOncogenicity                            0
SCVsForAggregateGermlineClassification              0
SCVsForAggregateSomaticClinicalImpact               0
SCVsForAggregateOncogenicityClassification          0
dtype: Int64

In [67]:
df.loc[df["GeneSymbol"] == "-", "GeneSymbol"] = pd.NA

In [68]:
(df == "-").sum().sort_values(ascending=False)

Guidelines                                    8371588
ReviewStatus                                   490808
PhenotypeList                                    1599
AlternateAllele                                   556
ReferenceAllele                                    70
HGNC_ID                                             0
GeneSymbol                                          0
GeneID                                              0
#AlleleID                                           0
Type                                                0
Name                                                0
nsv/esv (dbVar)                                     0
RS# (dbSNP)                                         0
LastEvaluated                                       0
ClinSigSimple                                       0
ClinicalSignificance                                0
RCVaccession                                        0
PhenotypeIDS                                        0
Origin                                              0
Chromosome                                          0
ChromosomeAccession                                 0
Assembly                                            0
OriginSimple                                        0
Start                                               0
Stop                                                0
Cytogenetic                                         0
NumberSubmitters                                    0
TestedInGTR                                         0
OtherIDs                                            0
SubmitterCategories                                 0
VariationID                                         0
PositionVCF                                         0
ReferenceAlleleVCF                                  0
AlternateAlleleVCF                                  0
SomaticClinicalImpact                               0
SomaticClinicalImpactLastEvaluated                  0
ReviewStatusClinicalImpact                          0
Oncogenicity                                        0
OncogenicityLastEvaluated                           0
ReviewStatusOncogenicity                            0
SCVsForAggregateGermlineClassification              0
SCVsForAggregateSomaticClinicalImpact               0
SCVsForAggregateOncogenicityClassification          0
dtype: Int64

In [69]:
(df == "na").sum().sort_values(ascending=False)

ReferenceAllele                               9048840
AlternateAllele                               9048325
ChromosomeAccession                              9480
Chromosome                                       9480
Assembly                                         9480
HGNC_ID                                             0
GeneSymbol                                          0
GeneID                                              0
#AlleleID                                           0
Type                                                0
Name                                                0
nsv/esv (dbVar)                                     0
RS# (dbSNP)                                         0
LastEvaluated                                       0
ClinSigSimple                                       0
ClinicalSignificance                                0
PhenotypeList                                       0
Origin                                              0
RCVaccession                                        0
OriginSimple                                        0
PhenotypeIDS                                        0
Stop                                                0
Start                                               0
Cytogenetic                                         0
ReviewStatus                                        0
NumberSubmitters                                    0
Guidelines                                          0
TestedInGTR                                         0
OtherIDs                                            0
SubmitterCategories                                 0
VariationID                                         0
PositionVCF                                         0
ReferenceAlleleVCF                                  0
AlternateAlleleVCF                                  0
SomaticClinicalImpact                               0
SomaticClinicalImpactLastEvaluated                  0
ReviewStatusClinicalImpact                          0
Oncogenicity                                        0
OncogenicityLastEvaluated                           0
ReviewStatusOncogenicity                            0
SCVsForAggregateGermlineClassification              0
SCVsForAggregateSomaticClinicalImpact               0
SCVsForAggregateOncogenicityClassification          0
dtype: Int64

In [70]:
df.loc[df["ReferenceAllele"] == "na", "ReferenceAllele"] = pd.NA
df.loc[df["AlternateAllele"] == "na", "AlternateAllele"] = pd.NA
df.loc[df["Chromosome"] == "na", "Chromosome"] = pd.NA
df.loc[df["ChromosomeAccession"] == "na", "ChromosomeAccession"] = pd.NA
df.loc[df["Assembly"] == "na", "Assembly"] = pd.NA

In [71]:
(df == "na").sum().sort_values(ascending=False)

#AlleleID                                     0
Type                                          0
Name                                          0
GeneID                                        0
GeneSymbol                                    0
HGNC_ID                                       0
ClinicalSignificance                          0
ClinSigSimple                                 0
LastEvaluated                                 0
RS# (dbSNP)                                   0
nsv/esv (dbVar)                               0
RCVaccession                                  0
PhenotypeIDS                                  0
PhenotypeList                                 0
Origin                                        0
OriginSimple                                  0
Assembly                                      0
ChromosomeAccession                           0
Chromosome                                    0
Start                                         0
Stop                                          0
ReferenceAllele                               0
AlternateAllele                               0
Cytogenetic                                   0
ReviewStatus                                  0
NumberSubmitters                              0
Guidelines                                    0
TestedInGTR                                   0
OtherIDs                                      0
SubmitterCategories                           0
VariationID                                   0
PositionVCF                                   0
ReferenceAlleleVCF                            0
AlternateAlleleVCF                            0
SomaticClinicalImpact                         0
SomaticClinicalImpactLastEvaluated            0
ReviewStatusClinicalImpact                    0
Oncogenicity                                  0
OncogenicityLastEvaluated                     0
ReviewStatusOncogenicity                      0
SCVsForAggregateGermlineClassification        0
SCVsForAggregateSomaticClinicalImpact         0
SCVsForAggregateOncogenicityClassification    0
dtype: Int64

In [72]:
(df == "").sum().sort_values(ascending=False)

#AlleleID                                     0
Type                                          0
Name                                          0
GeneID                                        0
GeneSymbol                                    0
HGNC_ID                                       0
ClinicalSignificance                          0
ClinSigSimple                                 0
LastEvaluated                                 0
RS# (dbSNP)                                   0
nsv/esv (dbVar)                               0
RCVaccession                                  0
PhenotypeIDS                                  0
PhenotypeList                                 0
Origin                                        0
OriginSimple                                  0
Assembly                                      0
ChromosomeAccession                           0
Chromosome                                    0
Start                                         0
Stop                                          0
ReferenceAllele                               0
AlternateAllele                               0
Cytogenetic                                   0
ReviewStatus                                  0
NumberSubmitters                              0
Guidelines                                    0
TestedInGTR                                   0
OtherIDs                                      0
SubmitterCategories                           0
VariationID                                   0
PositionVCF                                   0
ReferenceAlleleVCF                            0
AlternateAlleleVCF                            0
SomaticClinicalImpact                         0
SomaticClinicalImpactLastEvaluated            0
ReviewStatusClinicalImpact                    0
Oncogenicity                                  0
OncogenicityLastEvaluated                     0
ReviewStatusOncogenicity                      0
SCVsForAggregateGermlineClassification        0
SCVsForAggregateSomaticClinicalImpact         0
SCVsForAggregateOncogenicityClassification    0
dtype: Int64

### DECIDING HOW TO BREAK DOWN INTO TABLES

In [73]:
df["#AlleleID"].nunique()

4558681

In [74]:
df["GeneID"].nunique()

20273

In [75]:
df["VariationID"].nunique()

4558681

In [76]:
print(df.shape[0] / 4558681)

1.9849956599288259

In [77]:
df.groupby("#AlleleID").size().value_counts().sort_index()

1      73109
2    4483203
3         29
4       2340
Name: count, dtype: int64

In [78]:
df.groupby("#AlleleID")["Assembly"].nunique().value_counts()

Assembly
2    4485495
1      63706
0       9480
Name: count, dtype: int64

In [79]:
df[df.groupby("#AlleleID")["#AlleleID"].transform("size") == 2][["#AlleleID", "Assembly"]]

         #AlleleID Assembly
0            15041   GRCh37
1            15041   GRCh38
2            15042   GRCh37
3            15042   GRCh38
4            15043   GRCh37
...            ...      ...
9048951    4997580   GRCh38
9048952    4997581   GRCh37
9048953    4997581   GRCh38
9048958    4997586   GRCh37
9048959    4997586   GRCh38

[8966406 rows x 2 columns]

In [80]:
df[df.groupby("#AlleleID")["#AlleleID"].transform("size") == 3]

,#AlleleID,Type,Name,GeneID,GeneSymbol,HGNC_ID,ClinicalSignificance,ClinSigSimple,LastEvaluated,RS# (dbSNP),nsv/esv (dbVar),RCVaccession,PhenotypeIDS,PhenotypeList,Origin,OriginSimple,Assembly,ChromosomeAccession,Chromosome,Start,Stop,ReferenceAllele,AlternateAllele,Cytogenetic,ReviewStatus,NumberSubmitters,Guidelines,TestedInGTR,OtherIDs,SubmitterCategories,VariationID,PositionVCF,ReferenceAlleleVCF,AlternateAlleleVCF,SomaticClinicalImpact,SomaticClinicalImpactLastEvaluated,ReviewStatusClinicalImpact,Oncogenicity,OncogenicityLastEvaluated,ReviewStatusOncogenicity,SCVsForAggregateGermlineClassification,SCVsForAggregateSomaticClinicalImpact,SCVsForAggregateOncogenicityClassification
167304,162810,copy number gain,GRCh38/hg38 17q12(chr17:36566143-37808105)x3,<NA>,subset of 31 genes: HNF1B,NaN,Uncertain significance,0,2018-06-02,<NA>,nsv995056,RCV000141558,NaN,See cases,de novo,germline,GRCh37,NC_000017.10,17,34817452,36168075,NaN,NaN,17q12,no assertion criteria provided,1,-,N,dbVar:nssv3395743,2,153059,<NA>,NaN,NaN,NaN,NaT,NaN,NaN,NaT,NaN,SCV000182475,NaN,NaN
167305,162810,copy number gain,GRCh38/hg38 17q12(chr17:36566143-37808105)x3,<NA>,subset of 31 genes: HNF1B,NaN,Uncertain significance,0,2018-06-02,<NA>,nsv995056,RCV000141558,NaN,See cases,de novo,germline,GRCh38,NC_000017.11,17,36566143,37808105,NaN,NaN,17q12,no assertion criteria provided,1,-,N,dbVar:nssv3395743,2,153059,<NA>,NaN,NaN,NaN,NaT,NaN,NaN,NaT,NaN,SCV000182475,NaN,NaN
167306,162810,copy number gain,GRCh38/hg38 17q12(chr17:36566143-37808105)x3,<NA>,subset of 31 genes: HNF1B,NaN,Uncertain significance,0,2018-06-02,<NA>,nsv995056,RCV000141558,NaN,See cases,de novo,germline,GRCh38,NT_187614.1,17,801047,2047140,NaN,NaN,17q12,no assertion criteria provided,1,-,N,dbVar:nssv3395743,2,153059,<NA>,NaN,NaN,NaN,NaT,NaN,NaN,NaT,NaN,SCV000182475,NaN,NaN
174449,167290,Deletion,Single allele,<NA>,NaN,NaN,not provided,0,NaT,<NA>,NaN,RCV000161856|RCV000161857|RCV000161858,MedGen:C0232989|Human Phenotype Ontology:HP:00...,Normal pregnancy|Small for gestational age|Pre...,unknown,unknown,GRCh37,NC_000019.9,19,20626179,20707568,NaN,NaN,19p12,no classification provided,1,-,N,NaN,2,157430,<NA>,NaN,NaN,NaN,NaT,NaN,NaN,NaT,NaN,SCV000191813|SCV000191814|SCV000191815,NaN,NaN
174450,167290,Deletion,Single allele,<NA>,NaN,NaN,not provided,0,NaT,<NA>,NaN,RCV000161856|RCV000161857|RCV000161858,MedGen:C0232989|Human Phenotype Ontology:HP:00...,Normal pregnancy|Small for gestational age|Pre...,unknown,unknown,GRCh37,NW_003571053.2,19,360626,442015,NaN,NaN,19p12,no classification provided,1,-,N,NaN,2,157430,<NA>,NaN,NaN,NaN,NaT,NaN,NaN,NaT,NaN,SCV000191813|SCV000191814|SCV000191815,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7798794,4368363,single nucleotide variant,NM_001286820.2(FRG2):c.277C>T (p.Arg93Trp),448831,FRG2,HGNC:19136,Uncertain significance,0,2025-08-23,<NA>,NaN,RCV005847439,MedGen:CN169374,not specified,germline,germline,GRCh37,NT_167222.1,Un,31410,31410,NaN,NaN,4q35.2,"criteria provided, single submitter",1,-,N,NaN,2,4259797,31410,G,A,NaN,NaT,NaN,NaN,NaT,NaN,SCV006528419,NaN,NaN
7798795,4368363,single nucleotide variant,NM_001286820.2(FRG2):c.277C>T (p.Arg93Trp),448831,FRG2,HGNC:19136,Uncertain significance,0,2025-08-23,<NA>,NaN,RCV005847439,MedGen:CN169374,not specified,germline,germline,GRCh38,NC_000004.12,4,190026441,190026441,NaN,NaN,4q35.2,"criteria provided, single submitter",1,-,N,NaN,2,4259797,190026441,G,A,NaN,NaT,NaN,NaN,NaT,NaN,SCV006528419,NaN,NaN
7798796,4368364,single nucleotide variant,NM_001286820.2(FRG2):c.326A>G (p.Asp109Gly),448831,FRG2,HGNC:19136,Uncertain significance,0,2025-07-31,<NA>,NaN,RCV005833915,MedGen:CN169374,not specified,germline,germline,GRCh37,NC_000004.11,4,190947547,190947547,NaN,NaN,4q35.2,"criteria provided, single submitter",1,-,N,NaN,2,4259798,190947547,T,C,NaN,NaT,NaN,NaN,NaT,NaN,SCV006528420,NaN,NaN
7798797,4368364,single nucleotide variant,NM_001286820.2(FRG2):c.326A>G (p.Asp109Gly),448831,FRG2,HGNC:19136,Uncertain significance,0,2025-07-31,<NA>,NaN,RCV005833915,MedGen:CN169374,not specified,germline,germline,GRCh37,NT_167222.1,Un,31361,31361,NaN,NaN,4q35.2,"criteria provided, single submitter",1,-,N,NaN,2,4259798,31361,T,C,NaN,NaT,NaN,NaN,NaT,NaN,SCV006528420,NaN,NaN
7798798,4368364,single nucleotide variant,NM_001286820.2(FRG2):c.326A>G (p.Asp109Gly),448831,FRG2,HGNC:19136,Uncertain significance,0,2025-07-31,<NA>,NaN,RCV005833915,MedGen:CN169374,not specified,germline,germline,GRCh38,NC_000004.12,4,190026392,190026392,NaN,NaN,4q35.2,"criteria provided, single submitter",1,-,N,NaN,2,4259798,190026392,T,C,NaN,NaT,NaN,NaN,NaT,NaN,SCV006528420,NaN,NaN

In [81]:
df[df.groupby("#AlleleID")["#AlleleID"].transform("size") == 4][["#AlleleID", "VariationID", "Assembly", "ChromosomeAccession", "Start", "Stop"]]

         #AlleleID  VariationID Assembly ChromosomeAccession    Start     Stop
18022        24911         9872   GRCh37        NC_000023.10   601772   601772
18023        24911         9872   GRCh37         NC_000024.9   551772   551772
18024        24911         9872   GRCh38        NC_000023.11   641037   641037
18025        24911         9872   GRCh38        NC_000024.10   641037   641037
18026        24912         9873   GRCh37        NC_000023.10   601786   601786
...            ...          ...      ...                 ...      ...      ...
9041462    4993742      4882457   GRCh38        NC_000024.10  2243192  2243192
9048676    4997443      4886618   GRCh37        NC_000023.10   601831   601831
9048677    4997443      4886618   GRCh37         NC_000024.9   551831   551831
9048678    4997443      4886618   GRCh38        NC_000023.11   641096   641096
9048679    4997443      4886618   GRCh38        NC_000024.10   641096   641096

[9360 rows x 6 columns]

In [82]:
df.groupby("#AlleleID")["VariationID"].nunique().value_counts()

VariationID
1    4558681
Name: count, dtype: int64

In [83]:
df[df["#AlleleID"] == df["VariationID"]].shape

(16, 43)

In [84]:
df.groupby("VariationID")["#AlleleID"].nunique().value_counts()

#AlleleID
1    4558681
Name: count, dtype: int64

In [85]:
df.duplicated().sum()

np.int64(0)

In [86]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9048962 entries, 0 to 9048961
Data columns (total 43 columns):
 #   Column                                      Dtype
---  ------                                      -----
 0   #AlleleID                                   int64
 1   Type                                        str
 2   Name                                        str
 3   GeneID                                      Int64
 4   GeneSymbol                                  str
 5   HGNC_ID                                     str
 6   ClinicalSignificance                        str
 7   ClinSigSimple                               int64
 8   LastEvaluated                               datetime64[us]
 9   RS# (dbSNP)                                 Int64
 10  nsv/esv (dbVar)                             str
 11  RCVaccession                                str
 12  PhenotypeIDS                                str
 13  PhenotypeList                               str
 14  Origin                                      str
 15  OriginSimple                                str
 16  Assembly                                    str
 17  ChromosomeAccession                         str
 18  Chromosome                                  str
 19  Start                                       Int64
 20  Stop                                        Int64
 21  ReferenceAllele                             str
 22  AlternateAllele                             str
 23  Cytogenetic                                 str
 24  ReviewStatus                                str
 25  NumberSubmitters                            int64
 26  Guidelines                                  str
 27  TestedInGTR                                 str
 28  OtherIDs                                    str
 29  SubmitterCategories                         int64
 30  VariationID                                 int64
 31  PositionVCF                                 Int64
 32  ReferenceAlleleVCF                          str
 33  AlternateAlleleVCF                          str
 34  SomaticClinicalImpact                       str
 35  SomaticClinicalImpactLastEvaluated          datetime64[us]
 36  ReviewStatusClinicalImpact                  str
 37  Oncogenicity                                str
 38  OncogenicityLastEvaluated                   datetime64[us]
 39  ReviewStatusOncogenicity                    str
 40  SCVsForAggregateGermlineClassification      str
 41  SCVsForAggregateSomaticClinicalImpact       str
 42  SCVsForAggregateOncogenicityClassification  str
dtypes: Int64(5), datetime64[us](3), int64(5), str(30)
memory usage: 5.6 GB

In [87]:
df["TestedInGTR"].value_counts(dropna=False)

TestedInGTR
N    9047746
Y       1216
Name: count, dtype: int64

In [88]:
df["TestedInGTR"] = df["TestedInGTR"].map({"Y": True, "N": False})

In [89]:
df["TestedInGTR"].dtype

dtype('bool')

### SCHEMA BUILDING

In [90]:
df.groupby("#AlleleID")["Type"].nunique().value_counts()

Type
1    4558681
Name: count, dtype: int64

In [91]:
type_check = df.groupby("#AlleleID")["Type"].agg(["nunique", "count", "size"])
type_check[(type_check["nunique"] == 1) & (type_check["count"] < type_check["size"])]

Empty DataFrame
Columns: [nunique, count, size]
Index: []

In [92]:
df.groupby("#AlleleID")["Name"].nunique().value_counts()

Name
1    4558681
Name: count, dtype: int64

In [93]:
name_check = df.groupby("#AlleleID")["Name"].agg(["nunique", "count", "size"])
name_check[(name_check["nunique"] == 1) & (name_check["count"] < name_check["size"])]

Empty DataFrame
Columns: [nunique, count, size]
Index: []

In [94]:
df.groupby("#AlleleID")["GeneID"].nunique().value_counts()

GeneID
1    4510800
0      47881
Name: count, dtype: int64

In [95]:
geneid_check = df.groupby("#AlleleID")["GeneID"].agg(["nunique", "count", "size"])
geneid_check[(geneid_check["nunique"] == 1) & (geneid_check["count"] < geneid_check["size"])]

Empty DataFrame
Columns: [nunique, count, size]
Index: []

In [96]:
df.groupby("#AlleleID")["HGNC_ID"].nunique().value_counts()

HGNC_ID
1    4510269
0      48412
Name: count, dtype: int64

In [97]:
hgncid_check = df.groupby("#AlleleID")["HGNC_ID"].agg(["nunique", "count", "size"])
hgncid_check[(hgncid_check["nunique"] == 1) & (hgncid_check["count"] < hgncid_check["size"])]

Empty DataFrame
Columns: [nunique, count, size]
Index: []

In [98]:
df.groupby("#AlleleID")["GeneSymbol"].nunique().value_counts()

GeneSymbol
1    4550430
0       8251
Name: count, dtype: int64

In [99]:
gs_check = df.groupby("#AlleleID")["GeneSymbol"].agg(["nunique", "count", "size"])
gs_check[(gs_check["nunique"] == 1) & (gs_check["count"] < gs_check["size"])]

Empty DataFrame
Columns: [nunique, count, size]
Index: []

In [100]:
df.groupby("#AlleleID")["ClinicalSignificance"].nunique().value_counts()

ClinicalSignificance
1    4314396
0     244285
Name: count, dtype: int64

In [101]:
cs_check = df.groupby("#AlleleID")["ClinicalSignificance"].agg(["nunique", "count", "size"])
cs_check[(cs_check["nunique"] == 1) & (cs_check["count"] < cs_check["size"])]

Empty DataFrame
Columns: [nunique, count, size]
Index: []

In [102]:
df.groupby("#AlleleID")["ClinSigSimple"].nunique().value_counts()

ClinSigSimple
1    4558681
Name: count, dtype: int64

In [103]:
css_check = df.groupby("#AlleleID")["ClinSigSimple"].agg(["nunique", "count", "size"])
css_check[(css_check["nunique"] == 1) & (css_check["count"] < css_check["size"])]

Empty DataFrame
Columns: [nunique, count, size]
Index: []

In [104]:
df.groupby("#AlleleID")["LastEvaluated"].nunique().value_counts()

LastEvaluated
1    4271358
0     287323
Name: count, dtype: int64

In [105]:
le_check = df.groupby("#AlleleID")["LastEvaluated"].agg(["nunique", "count", "size"])
le_check[(le_check["nunique"] == 1) & (le_check["count"] < le_check["size"])]

Empty DataFrame
Columns: [nunique, count, size]
Index: []

In [106]:
df.groupby("#AlleleID")["RS# (dbSNP)"].nunique().value_counts()

RS# (dbSNP)
1    2896416
0    1662265
Name: count, dtype: int64

In [107]:
dbsnp_check = df.groupby("#AlleleID")["RS# (dbSNP)"].agg(["nunique", "count", "size"])
dbsnp_check[(dbsnp_check["nunique"] == 1) & (dbsnp_check["count"] < dbsnp_check["size"])]

Empty DataFrame
Columns: [nunique, count, size]
Index: []

In [108]:
df.groupby("#AlleleID")["nsv/esv (dbVar)"].nunique().value_counts()

nsv/esv (dbVar)
0    4536196
1      22485
Name: count, dtype: int64

In [109]:
dbvar_check = df.groupby("#AlleleID")["nsv/esv (dbVar)"].agg(["nunique", "count", "size"])
dbvar_check[(dbvar_check["nunique"] == 1) & (dbvar_check["count"] < dbvar_check["size"])]

Empty DataFrame
Columns: [nunique, count, size]
Index: []

In [110]:
df.groupby("#AlleleID")["RCVaccession"].nunique().value_counts()

RCVaccession
1    4557957
0        724
Name: count, dtype: int64

In [111]:
rcva_check = df.groupby("#AlleleID")["RCVaccession"].agg(["nunique", "count", "size"])
rcva_check[(rcva_check["nunique"] == 1) & (rcva_check["count"] < rcva_check["size"])]

Empty DataFrame
Columns: [nunique, count, size]
Index: []

In [112]:
df.groupby("#AlleleID")["PhenotypeIDS"].nunique().value_counts()

PhenotypeIDS
1    4480773
0      77908
Name: count, dtype: int64

In [113]:
phenoids_check = df.groupby("#AlleleID")["PhenotypeIDS"].agg(["nunique", "count", "size"])
phenoids_check[(phenoids_check["nunique"] == 1) & (phenoids_check["count"] < phenoids_check["size"])]

Empty DataFrame
Columns: [nunique, count, size]
Index: []

In [114]:
df["PhenotypeIDS"].dropna().head(10)

0    MONDO:MONDO:0013342,MedGen:C3150901,OMIM:61364...
1    MONDO:MONDO:0013342,MedGen:C3150901,OMIM:61364...
2    MONDO:MONDO:0013342,MedGen:C3150901,OMIM:61364...
3    MONDO:MONDO:0013342,MedGen:C3150901,OMIM:61364...
4    MONDO:MONDO:0033005,MedGen:C4551772,OMIM:25130...
5    MONDO:MONDO:0033005,MedGen:C4551772,OMIM:25130...
6    MONDO:MONDO:0032624,MedGen:C4748791,OMIM:61824...
7    MONDO:MONDO:0032624,MedGen:C4748791,OMIM:61824...
8      MONDO:MONDO:0032624,MedGen:C4748791,OMIM:618241
9      MONDO:MONDO:0032624,MedGen:C4748791,OMIM:618241
Name: PhenotypeIDS, dtype: str

In [115]:
df.head()

,#AlleleID,Type,Name,GeneID,GeneSymbol,HGNC_ID,ClinicalSignificance,ClinSigSimple,LastEvaluated,RS# (dbSNP),nsv/esv (dbVar),RCVaccession,PhenotypeIDS,PhenotypeList,Origin,OriginSimple,Assembly,ChromosomeAccession,Chromosome,Start,Stop,ReferenceAllele,AlternateAllele,Cytogenetic,ReviewStatus,NumberSubmitters,Guidelines,TestedInGTR,OtherIDs,SubmitterCategories,VariationID,PositionVCF,ReferenceAlleleVCF,AlternateAlleleVCF,SomaticClinicalImpact,SomaticClinicalImpactLastEvaluated,ReviewStatusClinicalImpact,Oncogenicity,OncogenicityLastEvaluated,ReviewStatusOncogenicity,SCVsForAggregateGermlineClassification,SCVsForAggregateSomaticClinicalImpact,SCVsForAggregateOncogenicityClassification
0,15041,Indel,NM_014855.3(AP5Z1):c.80_83delinsTGCTGTAAACTGTA...,9907,AP5Z1,HGNC:22197,Pathogenic/Likely pathogenic,1,2024-12-17,397704705,NaN,RCV000000012|RCV005255549|RCV004998069,"MONDO:MONDO:0013342,MedGen:C3150901,OMIM:61364...",Hereditary spastic paraplegia 48|Macular dystr...,germline;unknown,germline,GRCh37,NC_000007.13,7,4820844,4820847,NaN,NaN,7p22.1,"criteria provided, multiple submitters, no con...",4,-,False,"ClinGen:CA215070,OMIM:613653.0001",3,2,4820844,GGAT,TGCTGTAAACTGTAACTGTAAA,NaN,NaT,NaN,NaN,NaT,NaN,SCV001451119|SCV005622007|SCV005909190,NaN,NaN
1,15041,Indel,NM_014855.3(AP5Z1):c.80_83delinsTGCTGTAAACTGTA...,9907,AP5Z1,HGNC:22197,Pathogenic/Likely pathogenic,1,2024-12-17,397704705,NaN,RCV000000012|RCV005255549|RCV004998069,"MONDO:MONDO:0013342,MedGen:C3150901,OMIM:61364...",Hereditary spastic paraplegia 48|Macular dystr...,germline;unknown,germline,GRCh38,NC_000007.14,7,4781213,4781216,NaN,NaN,7p22.1,"criteria provided, multiple submitters, no con...",4,-,False,"ClinGen:CA215070,OMIM:613653.0001",3,2,4781213,GGAT,TGCTGTAAACTGTAACTGTAAA,NaN,NaT,NaN,NaN,NaT,NaN,SCV001451119|SCV005622007|SCV005909190,NaN,NaN
2,15042,Deletion,NM_014855.3(AP5Z1):c.1413_1426del (p.Leu473fs),9907,AP5Z1,HGNC:22197,Pathogenic,1,2010-06-29,397704709,NaN,RCV000000013,"MONDO:MONDO:0013342,MedGen:C3150901,OMIM:61364...",Hereditary spastic paraplegia 48,germline,germline,GRCh37,NC_000007.13,7,4827361,4827374,NaN,NaN,7p22.1,no assertion criteria provided,1,-,False,"ClinGen:CA215072,OMIM:613653.0002",1,3,4827360,GCTGCTGGACCTGCC,G,NaN,NaT,NaN,NaN,NaT,NaN,SCV000020156,NaN,NaN
3,15042,Deletion,NM_014855.3(AP5Z1):c.1413_1426del (p.Leu473fs),9907,AP5Z1,HGNC:22197,Pathogenic,1,2010-06-29,397704709,NaN,RCV000000013,"MONDO:MONDO:0013342,MedGen:C3150901,OMIM:61364...",Hereditary spastic paraplegia 48,germline,germline,GRCh38,NC_000007.14,7,4787730,4787743,NaN,NaN,7p22.1,no assertion criteria provided,1,-,False,"ClinGen:CA215072,OMIM:613653.0002",1,3,4787729,GCTGCTGGACCTGCC,G,NaN,NaT,NaN,NaN,NaT,NaN,SCV000020156,NaN,NaN
4,15043,single nucleotide variant,NM_014630.3(ZNF592):c.3136G>A (p.Gly1046Arg),9640,ZNF592,HGNC:28986,Uncertain significance,0,2015-06-29,150829393,NaN,RCV000000014,"MONDO:MONDO:0033005,MedGen:C4551772,OMIM:25130...",Galloway-Mowat syndrome 1,germline,germline,GRCh37,NC_000015.9,15,85342440,85342440,NaN,NaN,15q25.3,no assertion criteria provided,1,-,False,"ClinGen:CA210674,UniProtKB:Q92610#VAR_064583,O...",1,4,85342440,G,A,NaN,NaT,NaN,NaN,NaT,NaN,SCV000020157,NaN,NaN

In [116]:
df["SCVsForAggregateSomaticClinicalImpact"].value_counts()

SCVsForAggregateSomaticClinicalImpact
SCV007104928    2
SCV007104906    2
SCV007104371    2
SCV007104365    2
SCV007104369    2
               ..
SCV007615622    2
SCV007615623    2
SCV007655975    2
SCV005061371    1
SCV005687767    1
Name: count, Length: 1316, dtype: int64

In [117]:
df["SCVsForAggregateOncogenicityClassification"].value_counts()

SCVsForAggregateOncogenicityClassification
SCV005093976    2
SCV007129937    2
SCV005094482    2
SCV005871982    2
SCV005871701    2
               ..
SCV005438029    1
SCV005438010    1
SCV005442829    1
SCV007669889    1
SCV007669890    1
Name: count, Length: 1905, dtype: int64

In [118]:
df["Origin"].value_counts()

Origin
germline                                  7918259
not applicable                             489088
germline;unknown                           312639
unknown                                    142751
germline;not applicable                     48600
                                           ...
biparental;not applicable;unknown               2
de novo;not applicable;somatic;unknown          2
inherited;maternal;not applicable               2
biparental;de novo;maternal;paternal            2
inherited;not applicable;paternal               1
Name: count, Length: 181, dtype: int64

In [119]:
df[df.groupby("#AlleleID")["#AlleleID"].transform("size") == 2][
    ["#AlleleID", "Assembly", "ChromosomeAccession",
     "Chromosome", "Start", "Stop",
     "ReferenceAllele", "AlternateAllele"]
].head(20)

,#AlleleID,Assembly,ChromosomeAccession,Chromosome,Start,Stop,ReferenceAllele,AlternateAllele
0,15041,GRCh37,NC_000007.13,7,4820844,4820847,NaN,NaN
1,15041,GRCh38,NC_000007.14,7,4781213,4781216,NaN,NaN
2,15042,GRCh37,NC_000007.13,7,4827361,4827374,NaN,NaN
3,15042,GRCh38,NC_000007.14,7,4787730,4787743,NaN,NaN
4,15043,GRCh37,NC_000015.9,15,85342440,85342440,NaN,NaN
5,15043,GRCh38,NC_000015.10,15,84799209,84799209,NaN,NaN
6,15044,GRCh37,NC_000011.9,11,126145284,126145284,NaN,NaN
7,15044,GRCh38,NC_000011.10,11,126275389,126275389,NaN,NaN
8,15045,GRCh37,NC_000011.9,11,126147412,126147412,NaN,NaN
9,15045,GRCh38,NC_000011.10,11,126277517,126277517,NaN,NaN
10,15046,GRCh37,NC_000014.8,14,32031331,32031331,NaN,NaN
11,15046,GRCh38,NC_000014.9,14,31562125,31562125,NaN,NaN
12,15048,GRCh37,NC_000006.11,6,26093141,26093141,NaN,NaN
13,15048,GRCh38,NC_000006.12,6,26092913,26092913,NaN,NaN
14,15049,GRCh37,NC_000006.11,6,26091179,26091179,NaN,NaN
15,15049,GRCh38,NC_000006.12,6,26090951,26090951,NaN,NaN
16,15050,GRCh37,NC_000006.11,6,26091185,26091185,NaN,NaN
17,15050,GRCh38,NC_000006.12,6,26090957,26090957,NaN,NaN
18,15051,GRCh37,NC_000006.11,6,26091306,26091306,NaN,NaN
19,15051,GRCh38,NC_000006.12,6,26091078,26091078,NaN,NaN

In [120]:
df[df.groupby("#AlleleID")["#AlleleID"].transform("size") == 2].head(4).T

,0,1,2,3
#AlleleID,15041,15041,15042,15042
Type,Indel,Indel,Deletion,Deletion
Name,NM_014855.3(AP5Z1):c.80_83delinsTGCTGTAAACTGTA...,NM_014855.3(AP5Z1):c.80_83delinsTGCTGTAAACTGTA...,NM_014855.3(AP5Z1):c.1413_1426del (p.Leu473fs),NM_014855.3(AP5Z1):c.1413_1426del (p.Leu473fs)
GeneID,9907,9907,9907,9907
GeneSymbol,AP5Z1,AP5Z1,AP5Z1,AP5Z1
HGNC_ID,HGNC:22197,HGNC:22197,HGNC:22197,HGNC:22197
ClinicalSignificance,Pathogenic/Likely pathogenic,Pathogenic/Likely pathogenic,Pathogenic,Pathogenic
ClinSigSimple,1,1,1,1
LastEvaluated,2024-12-17 00:00:00,2024-12-17 00:00:00,2010-06-29 00:00:00,2010-06-29 00:00:00
RS# (dbSNP),397704705,397704705,397704709,397704709
nsv/esv (dbVar),NaN,NaN,NaN,NaN
RCVaccession,RCV000000012|RCV005255549|RCV004998069,RCV000000012|RCV005255549|RCV004998069,RCV000000013,RCV000000013
PhenotypeIDS,"MONDO:MONDO:0013342,MedGen:C3150901,OMIM:61364...","MONDO:MONDO:0013342,MedGen:C3150901,OMIM:61364...","MONDO:MONDO:0013342,MedGen:C3150901,OMIM:61364...","MONDO:MONDO:0013342,MedGen:C3150901,OMIM:61364..."
PhenotypeList,Hereditary spastic paraplegia 48|Macular dystr...,Hereditary spastic paraplegia 48|Macular dystr...,Hereditary spastic paraplegia 48,Hereditary spastic paraplegia 48
Origin,germline;unknown,germline;unknown,germline,germline
OriginSimple,germline,germline,germline,germline
Assembly,GRCh37,GRCh38,GRCh37,GRCh38
ChromosomeAccession,NC_000007.13,NC_000007.14,NC_000007.13,NC_000007.14
Chromosome,7,7,7,7
Start,4820844,4781213,4827361,4787730
Stop,4820847,4781216,4827374,4787743
ReferenceAllele,NaN,NaN,NaN,NaN
AlternateAllele,NaN,NaN,NaN,NaN
Cytogenetic,7p22.1,7p22.1,7p22.1,7p22.1
ReviewStatus,"criteria provided, multiple submitters, no con...","criteria provided, multiple submitters, no con...",no assertion criteria provided,no assertion criteria provided
NumberSubmitters,4,4,1,1
Guidelines,-,-,-,-
TestedInGTR,False,False,False,False
OtherIDs,"ClinGen:CA215070,OMIM:613653.0001","ClinGen:CA215070,OMIM:613653.0001","ClinGen:CA215072,OMIM:613653.0002","ClinGen:CA215072,OMIM:613653.0002"
SubmitterCategories,3,3,1,1
VariationID,2,2,3,3
PositionVCF,4820844,4781213,4827360,4787729
ReferenceAlleleVCF,GGAT,GGAT,GCTGCTGGACCTGCC,GCTGCTGGACCTGCC
AlternateAlleleVCF,TGCTGTAAACTGTAACTGTAAA,TGCTGTAAACTGTAACTGTAAA,G,G
SomaticClinicalImpact,NaN,NaN,NaN,NaN
SomaticClinicalImpactLastEvaluated,NaT,NaT,NaT,NaT
ReviewStatusClinicalImpact,NaN,NaN,NaN,NaN
Oncogenicity,NaN,NaN,NaN,NaN
OncogenicityLastEvaluated,NaT,NaT,NaT,NaT
ReviewStatusOncogenicity,NaN,NaN,NaN,NaN
SCVsForAggregateGermlineClassification,SCV001451119|SCV005622007|SCV005909190,SCV001451119|SCV005622007|SCV005909190,SCV000020156,SCV000020156
SCVsForAggregateSomaticClinicalImpact,NaN,NaN,NaN,NaN
SCVsForAggregateOncogenicityClassification,NaN,NaN,NaN,NaN

In [121]:
df[df["#AlleleID"].isin([15041, 15042, 167304])].T

,0,1,2,3
#AlleleID,15041,15041,15042,15042
Type,Indel,Indel,Deletion,Deletion
Name,NM_014855.3(AP5Z1):c.80_83delinsTGCTGTAAACTGTA...,NM_014855.3(AP5Z1):c.80_83delinsTGCTGTAAACTGTA...,NM_014855.3(AP5Z1):c.1413_1426del (p.Leu473fs),NM_014855.3(AP5Z1):c.1413_1426del (p.Leu473fs)
GeneID,9907,9907,9907,9907
GeneSymbol,AP5Z1,AP5Z1,AP5Z1,AP5Z1
HGNC_ID,HGNC:22197,HGNC:22197,HGNC:22197,HGNC:22197
ClinicalSignificance,Pathogenic/Likely pathogenic,Pathogenic/Likely pathogenic,Pathogenic,Pathogenic
ClinSigSimple,1,1,1,1
LastEvaluated,2024-12-17 00:00:00,2024-12-17 00:00:00,2010-06-29 00:00:00,2010-06-29 00:00:00
RS# (dbSNP),397704705,397704705,397704709,397704709
nsv/esv (dbVar),NaN,NaN,NaN,NaN
RCVaccession,RCV000000012|RCV005255549|RCV004998069,RCV000000012|RCV005255549|RCV004998069,RCV000000013,RCV000000013
PhenotypeIDS,"MONDO:MONDO:0013342,MedGen:C3150901,OMIM:61364...","MONDO:MONDO:0013342,MedGen:C3150901,OMIM:61364...","MONDO:MONDO:0013342,MedGen:C3150901,OMIM:61364...","MONDO:MONDO:0013342,MedGen:C3150901,OMIM:61364..."
PhenotypeList,Hereditary spastic paraplegia 48|Macular dystr...,Hereditary spastic paraplegia 48|Macular dystr...,Hereditary spastic paraplegia 48,Hereditary spastic paraplegia 48
Origin,germline;unknown,germline;unknown,germline,germline
OriginSimple,germline,germline,germline,germline
Assembly,GRCh37,GRCh38,GRCh37,GRCh38
ChromosomeAccession,NC_000007.13,NC_000007.14,NC_000007.13,NC_000007.14
Chromosome,7,7,7,7
Start,4820844,4781213,4827361,4787730
Stop,4820847,4781216,4827374,4787743
ReferenceAllele,NaN,NaN,NaN,NaN
AlternateAllele,NaN,NaN,NaN,NaN
Cytogenetic,7p22.1,7p22.1,7p22.1,7p22.1
ReviewStatus,"criteria provided, multiple submitters, no con...","criteria provided, multiple submitters, no con...",no assertion criteria provided,no assertion criteria provided
NumberSubmitters,4,4,1,1
Guidelines,-,-,-,-
TestedInGTR,False,False,False,False
OtherIDs,"ClinGen:CA215070,OMIM:613653.0001","ClinGen:CA215070,OMIM:613653.0001","ClinGen:CA215072,OMIM:613653.0002","ClinGen:CA215072,OMIM:613653.0002"
SubmitterCategories,3,3,1,1
VariationID,2,2,3,3
PositionVCF,4820844,4781213,4827360,4787729
ReferenceAlleleVCF,GGAT,GGAT,GCTGCTGGACCTGCC,GCTGCTGGACCTGCC
AlternateAlleleVCF,TGCTGTAAACTGTAACTGTAAA,TGCTGTAAACTGTAACTGTAAA,G,G
SomaticClinicalImpact,NaN,NaN,NaN,NaN
SomaticClinicalImpactLastEvaluated,NaT,NaT,NaT,NaT
ReviewStatusClinicalImpact,NaN,NaN,NaN,NaN
Oncogenicity,NaN,NaN,NaN,NaN
OncogenicityLastEvaluated,NaT,NaT,NaT,NaT
ReviewStatusOncogenicity,NaN,NaN,NaN,NaN
SCVsForAggregateGermlineClassification,SCV001451119|SCV005622007|SCV005909190,SCV001451119|SCV005622007|SCV005909190,SCV000020156,SCV000020156
SCVsForAggregateSomaticClinicalImpact,NaN,NaN,NaN,NaN
SCVsForAggregateOncogenicityClassification,NaN,NaN,NaN,NaN

In [122]:
for col in df.columns:
    n = df.groupby("#AlleleID")[col].nunique()
    print(col, (n > 1).sum())

#AlleleID 0
Type 0
Name 0
GeneID 0
GeneSymbol 0
HGNC_ID 0
ClinicalSignificance 0
ClinSigSimple 0
LastEvaluated 0
RS# (dbSNP) 0
nsv/esv (dbVar) 0
RCVaccession 0
PhenotypeIDS 0
PhenotypeList 0
Origin 0
OriginSimple 0
Assembly 4485495
ChromosomeAccession 4482439
Chromosome 2476
Start 4449477
Stop 4449750
ReferenceAllele 0
AlternateAllele 0
Cytogenetic 0
ReviewStatus 0
NumberSubmitters 0
Guidelines 0
TestedInGTR 0
OtherIDs 0
SubmitterCategories 0
VariationID 0
PositionVCF 4432339
ReferenceAlleleVCF 8481
AlternateAlleleVCF 7623
SomaticClinicalImpact 0
SomaticClinicalImpactLastEvaluated 0
ReviewStatusClinicalImpact 0
Oncogenicity 0
OncogenicityLastEvaluated 0
ReviewStatusOncogenicity 0
SCVsForAggregateGermlineClassification 0
SCVsForAggregateSomaticClinicalImpact 0
SCVsForAggregateOncogenicityClassification 0

In [123]:
df.groupby(["#AlleleID", "ChromosomeAccession"]).size().value_counts()

1    9033216
2       3133
Name: count, dtype: int64

In [124]:
df[df.duplicated(["#AlleleID", "ChromosomeAccession"], keep=False)].head(10).T

,17409,17410,17411,17412,17413,17414,17415,17416,17417,17418
#AlleleID,24587,24587,24588,24588,24589,24589,24590,24590,24591,24591
Type,single nucleotide variant,single nucleotide variant,single nucleotide variant,single nucleotide variant,single nucleotide variant,single nucleotide variant,Deletion,Deletion,single nucleotide variant,single nucleotide variant
Name,NC_012920.1(MT-TV):m.1606G>A,NC_012920.1(MT-TV):m.1606G>A,NC_012920.1(MT-TV):m.1624C>T,NC_012920.1(MT-TV):m.1624C>T,NC_012920.1(MT-TY):m.5874T>C,NC_012920.1(MT-TY):m.5874T>C,NC_012920.1(MT-TY):m.5888del,NC_012920.1(MT-TY):m.5888del,NC_012920.1(MT-TY):m.5877C>T,NC_012920.1(MT-TY):m.5877C>T
GeneID,4577,4577,4577,4577,4579,4579,4579,4579,4579,4579
GeneSymbol,MT-TV,MT-TV,MT-TV,MT-TV,MT-TY,MT-TY,MT-TY,MT-TY,MT-TY,MT-TY
HGNC_ID,HGNC:7500,HGNC:7500,HGNC:7500,HGNC:7500,HGNC:7502,HGNC:7502,HGNC:7502,HGNC:7502,HGNC:7502,HGNC:7502
ClinicalSignificance,Uncertain significance,Uncertain significance,Likely pathogenic,Likely pathogenic,Uncertain significance,Uncertain significance,Uncertain significance,Uncertain significance,Uncertain significance,Uncertain significance
ClinSigSimple,1,1,1,1,1,1,1,1,1,1
LastEvaluated,2022-06-30 00:00:00,2022-06-30 00:00:00,2024-09-24 00:00:00,2024-09-24 00:00:00,2024-06-10 00:00:00,2024-06-10 00:00:00,2024-06-24 00:00:00,2024-06-24 00:00:00,2024-06-24 00:00:00,2024-06-24 00:00:00
RS# (dbSNP),199476143,199476143,199476144,199476144,118203891,118203891,118203892,118203892,118203893,118203893
nsv/esv (dbVar),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
RCVaccession,RCV000010156|RCV000850660|RCV002260583,RCV000010156|RCV000850660|RCV002260583,RCV000010158|RCV000850667|RCV004554592|RCV0054...,RCV000010158|RCV000850667|RCV004554592|RCV0054...,RCV000010159|RCV000509556|RCV005251021,RCV000010159|RCV000509556|RCV005251021,RCV000010160|RCV005411284,RCV000010160|RCV005411284,RCV000010161|RCV005411285,RCV000010161|RCV005411285
PhenotypeIDS,"MedGen:C4016634|MONDO:MONDO:0010789,MedGen:C01...","MedGen:C4016634|MONDO:MONDO:0010789,MedGen:C01...","MONDO:MONDO:0009723,MedGen:C2931891,OMIM:25600...","MONDO:MONDO:0009723,MedGen:C2931891,OMIM:25600...",MedGen:C4016631|MedGen:C3661900|MONDO:MONDO:00...,MedGen:C4016631|MedGen:C3661900|MONDO:MONDO:00...,"MONDO:MONDO:0010787,MedGen:C0022541,OMIM:53000...","MONDO:MONDO:0010787,MedGen:C0022541,OMIM:53000...","MONDO:MONDO:0010787,MedGen:C0022541,OMIM:53000...","MONDO:MONDO:0010787,MedGen:C0022541,OMIM:53000..."
PhenotypeList,"Ataxia, progressive seizures, mental deteriora...","Ataxia, progressive seizures, mental deteriora...","Leigh syndrome|MELAS syndrome|Leigh syndrome, ...","Leigh syndrome|MELAS syndrome|Leigh syndrome, ...",Exercise intolerance and complex III deficienc...,Exercise intolerance and complex III deficienc...,Kearns-Sayre syndrome|Mitochondrial disease,Kearns-Sayre syndrome|Mitochondrial disease,Kearns-Sayre syndrome|Mitochondrial disease,Kearns-Sayre syndrome|Mitochondrial disease
Origin,germline,germline,germline,germline,germline;somatic;unknown,germline;somatic;unknown,de novo;germline;somatic,de novo;germline;somatic,germline;somatic,germline;somatic
OriginSimple,germline,germline,germline,germline,germline/somatic,germline/somatic,germline/somatic,germline/somatic,germline/somatic,germline/somatic
Assembly,GRCh37,GRCh38,GRCh37,GRCh38,GRCh37,GRCh38,GRCh37,GRCh38,GRCh37,GRCh38
ChromosomeAccession,NC_012920.1,NC_012920.1,NC_012920.1,NC_012920.1,NC_012920.1,NC_012920.1,NC_012920.1,NC_012920.1,NC_012920.1,NC_012920.1
Chromosome,MT,MT,MT,MT,MT,MT,MT,MT,MT,MT
Start,1606,1606,1624,1624,5874,5874,5885,5885,5877,5877
Stop,1606,1606,1624,1624,5874,5874,5885,5885,5877,5877
ReferenceAllele,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AlternateAllele,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Cytogenetic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ReviewStatus,reviewed by expert panel,reviewed by expert panel,reviewed by expert panel,reviewed by expert panel,reviewed by expert panel,reviewed by expert panel,reviewed by expert panel,reviewed by expert panel,reviewed by expert panel,reviewed by expert panel
NumberSubmitters,3,3,5,5,3,3,3,3,2,2
Guidelines,-,-,-,-,-,-,-,-,-,-
TestedInGTR,True,True,False,False,False,False,False,False,False,False
OtherIDs,"ClinGen:CA120536,OMIM:590105.0001","ClinGen:CA120536,OMIM:590105.0001","ClinGen:CA120537,OMIM:590105.0002","ClinGen:CA120537,OMIM:590105.0002","ClinGen:CA120538,OMIM:590100.0001","ClinGen:CA120538,OMIM:590100.0001","ClinGen:CA254829,OMIM:590100.0002","ClinGen:CA254829,OMIM:590100.0002","ClinGen:CA254830,OMIM:590100.0003","ClinGen:CA254830,OMIM:590100.0003"
SubmitterCategories,3,3,3,3,3,3,3,3,3,3
VariationID,9548,9548,9549,9549,9550,9550,9551,9551,9552,9552
PositionVCF,1606,1606,1624,1624,5874,5874,5884,5884,5877,5877
ReferenceAlleleVCF,G,G,C,C,T,T,AT,AT,C,C
AlternateAlleleVCF,A,A,T,T,C,C,A,A,T,T
SomaticClinicalImpact,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SomaticClinicalImpactLastEvaluated,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT
ReviewStatusClinicalImpact,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Oncogenicity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
OncogenicityLastEvaluated,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT
ReviewStatusOncogenicity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SCVsForAggregateGermlineClassification,SCV002540731,SCV002540731,SCV006082468,SCV006082468,SCV005901619,SCV005901619,SCV006079586,SCV006079586,SCV006079585,SCV006079585
SCVsForAggregateSomaticClinicalImpact,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SCVsForAggregateOncogenicityClassification,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [125]:
df.groupby(
    ["#AlleleID", "Assembly", "ChromosomeAccession"]
).size().value_counts()

1    9039482
Name: count, dtype: int64

In [126]:
location_cols = [
    "Chromosome",
    "Start",
    "Stop",
    "PositionVCF",
    "ReferenceAlleleVCF",
    "AlternateAlleleVCF"
]

for col in location_cols:
    check = df.groupby(["#AlleleID", "Assembly", "ChromosomeAccession"])[col].agg(["nunique", "count", "size"])

    inconsistent = check[(check["nunique"] > 1) | ((check["nunique"] == 1) & (check["count"] < check["size"]))]

    print(col, len(inconsistent))

Chromosome 0
Start 0
Stop 0
PositionVCF 0
ReferenceAlleleVCF 0
AlternateAlleleVCF 0

In [127]:
df.columns.tolist()

['#AlleleID',
 'Type',
 'Name',
 'GeneID',
 'GeneSymbol',
 'HGNC_ID',
 'ClinicalSignificance',
 'ClinSigSimple',
 'LastEvaluated',
 'RS# (dbSNP)',
 'nsv/esv (dbVar)',
 'RCVaccession',
 'PhenotypeIDS',
 'PhenotypeList',
 'Origin',
 'OriginSimple',
 'Assembly',
 'ChromosomeAccession',
 'Chromosome',
 'Start',
 'Stop',
 'ReferenceAllele',
 'AlternateAllele',
 'Cytogenetic',
 'ReviewStatus',
 'NumberSubmitters',
 'Guidelines',
 'TestedInGTR',
 'OtherIDs',
 'SubmitterCategories',
 'VariationID',
 'PositionVCF',
 'ReferenceAlleleVCF',
 'AlternateAlleleVCF',
 'SomaticClinicalImpact',
 'SomaticClinicalImpactLastEvaluated',
 'ReviewStatusClinicalImpact',
 'Oncogenicity',
 'OncogenicityLastEvaluated',
 'ReviewStatusOncogenicity',
 'SCVsForAggregateGermlineClassification',
 'SCVsForAggregateSomaticClinicalImpact',
 'SCVsForAggregateOncogenicityClassification']

In [128]:
df["Guidelines"].value_counts()

Guidelines
-                                      8371588
ACMG2013,ACMG2016,ACMG2021,ACMG2022     502717
ACMG2021,ACMG2022                       136472
ACMG2016,ACMG2021,ACMG2022               20513
ACMG2022                                 12077
ACMG2013                                  5595
Name: count, dtype: int64

In [129]:
from sqlalchemy import create_engine

In [130]:
engine = create_engine("postgresql+psycopg://postgres:postgres2026!@localhost:5432/clinvar")

In [131]:
with engine.connect() as conn:
    print("Connected!")

Connected!

In [132]:
df.columns.tolist()

['#AlleleID',
 'Type',
 'Name',
 'GeneID',
 'GeneSymbol',
 'HGNC_ID',
 'ClinicalSignificance',
 'ClinSigSimple',
 'LastEvaluated',
 'RS# (dbSNP)',
 'nsv/esv (dbVar)',
 'RCVaccession',
 'PhenotypeIDS',
 'PhenotypeList',
 'Origin',
 'OriginSimple',
 'Assembly',
 'ChromosomeAccession',
 'Chromosome',
 'Start',
 'Stop',
 'ReferenceAllele',
 'AlternateAllele',
 'Cytogenetic',
 'ReviewStatus',
 'NumberSubmitters',
 'Guidelines',
 'TestedInGTR',
 'OtherIDs',
 'SubmitterCategories',
 'VariationID',
 'PositionVCF',
 'ReferenceAlleleVCF',
 'AlternateAlleleVCF',
 'SomaticClinicalImpact',
 'SomaticClinicalImpactLastEvaluated',
 'ReviewStatusClinicalImpact',
 'Oncogenicity',
 'OncogenicityLastEvaluated',
 'ReviewStatusOncogenicity',
 'SCVsForAggregateGermlineClassification',
 'SCVsForAggregateSomaticClinicalImpact',
 'SCVsForAggregateOncogenicityClassification']

In [133]:
test_df = df.head(1000).copy()

In [134]:
allele_df = test_df[
    [
        "#AlleleID",
        "Type",
        "Name",
        "GeneID",
        "GeneSymbol",
        "HGNC_ID",
        "ClinicalSignificance",
        "ClinSigSimple",
        "LastEvaluated",
        "RS# (dbSNP)",
        "nsv/esv (dbVar)",
        "Origin",
        "OriginSimple",
        "ReviewStatus",
        "NumberSubmitters",
        "TestedInGTR",
        "VariationID",
        "SomaticClinicalImpact",
        "SomaticClinicalImpactLastEvaluated",
        "ReviewStatusClinicalImpact",
        "Oncogenicity",
        "OncogenicityLastEvaluated",
        "ReviewStatusOncogenicity",
    ]
].copy()

In [135]:
location_df = test_df[
    [
        "#AlleleID",
        "Assembly",
        "ChromosomeAccession",
        "Chromosome",
        "Start",
        "Stop",
        "ReferenceAllele",
        "AlternateAllele",
        "Cytogenetic",
        "PositionVCF",
        "ReferenceAlleleVCF",
        "AlternateAlleleVCF",
    ]
].copy()

In [136]:
allele_df = allele_df.rename(columns={
    "#AlleleID": "allele_id",
    "Type": "allele_type",
    "Name": "allele_name",
    "GeneID": "gene_id",
    "GeneSymbol": "gene_symbol",
    "HGNC_ID": "hgnc_id",

    "ClinicalSignificance": "clinical_significance",
    "ClinSigSimple": "clin_sig_simple",
    "LastEvaluated": "last_evaluated",

    "RS# (dbSNP)": "rs_db_snp",
    "nsv/esv (dbVar)": "nsv_esv_dbvar",

    "Origin": "origin",
    "OriginSimple": "origin_simple",

    "ReviewStatus": "review_status",
    "NumberSubmitters": "number_submitters",
    "TestedInGTR": "tested_in_gtr",

    "VariationID": "variation_id",

    "SomaticClinicalImpact": "somatic_clinical_impact",
    "SomaticClinicalImpactLastEvaluated": "somatic_clinical_impact_last_evaluated",
    "ReviewStatusClinicalImpact": "review_status_clinical_impact",

    "Oncogenicity": "oncogenicity",
    "OncogenicityLastEvaluated": "oncogenicity_last_evaluated",
    "ReviewStatusOncogenicity": "review_status_oncogenicity"
})

In [137]:
location_df = location_df.rename(columns={
    "#AlleleID": "allele_id",
    "Assembly": "genome_assembly",
    "ChromosomeAccession": "chromosome_accession",
    "Chromosome": "chromosome",
    "Start": "start_position",
    "Stop": "stop_position",
    "ReferenceAllele": "reference_allele",
    "AlternateAllele": "alternate_allele",
    "Cytogenetic": "cytogenetic",
    "PositionVCF": "position_vcf",
    "ReferenceAlleleVCF": "reference_allele_vcf",
    "AlternateAlleleVCF": "alternate_allele_vcf"
})

In [138]:
print(allele_df.columns.tolist())
print(location_df.columns.tolist())

['allele_id', 'allele_type', 'allele_name', 'gene_id', 'gene_symbol', 'hgnc_id', 'clinical_significance', 'clin_sig_simple', 'last_evaluated', 'rs_db_snp', 'nsv_esv_dbvar', 'origin', 'origin_simple', 'review_status', 'number_submitters', 'tested_in_gtr', 'variation_id', 'somatic_clinical_impact', 'somatic_clinical_impact_last_evaluated', 'review_status_clinical_impact', 'oncogenicity', 'oncogenicity_last_evaluated', 'review_status_oncogenicity']
['allele_id', 'genome_assembly', 'chromosome_accession', 'chromosome', 'start_position', 'stop_position', 'reference_allele', 'alternate_allele', 'cytogenetic', 'position_vcf', 'reference_allele_vcf', 'alternate_allele_vcf']

In [139]:
allele_df.shape

(1000, 23)

In [140]:
location_df.shape

(1000, 12)

In [141]:
allele_df = allele_df.drop_duplicates(subset="allele_id")

In [142]:
allele_df.shape

(506, 23)

In [143]:
# allele_df.to_sql("allele", engine, if_exists="append", index=False)

In [144]:
# location_df.to_sql("allele_location", engine, if_exists="append", index=False)

### SAVING CLEANED DATA

In [145]:
import pandas as pd
import pyarrow as pa

print("pandas:", pd.__version__)
print("pyarrow:", pa.__version__)

pandas: 3.0.5
pyarrow: 22.0.0

In [146]:
import sys
print(sys.executable)

c:\Users\limhe\Desktop\VS Code\VS Code\GenomeOps\.venv\Scripts\python.exe

In [147]:
!python -m pip show pyarrow

Name: pyarrow
Version: 22.0.0
Summary: Python library for Apache Arrow
Home-page: https://arrow.apache.org/
Author:
Author-email:
License: Apache Software License
Location: c:\Users\limhe\Desktop\VS Code\VS Code\GenomeOps\.venv\Lib\site-packages
Requires:
Required-by:

In [148]:
!python -m pip show pandas

Name: pandas
Version: 3.0.5
Summary: Powerful data structures for data analysis, time series, and statistics
Home-page: https://pandas.pydata.org
Author:
Author-email: The Pandas Development Team <pandas-dev@python.org>
License: BSD 3-Clause License

 Copyright (c) 2008-2011, AQR Capital Management, LLC, Lambda Foundry, Inc. and PyData Development Team
 All rights reserved.

 Copyright (c) 2011-2026, Open source contributors.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:

 * Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

 * Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

 * Neither the name of the copyright holder nor the names of its
   contributors may be used to endorse or promote products derived from
   this software without specific prior written permission.

 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

Location: c:\Users\limhe\Desktop\VS Code\VS Code\GenomeOps\.venv\Lib\site-packages
Requires: numpy, python-dateutil, tzdata
Required-by:

In [149]:
df.to_parquet("../data/processed/variant_summary_cleaned.parquet", index=False)

In [2]:
df = pd.read_parquet("../data/processed/variant_summary_cleaned.parquet")

In [3]:
df.shape

(9048962, 43)

In [4]:
allele_df = df[
    [
        "#AlleleID",
        "Type",
        "Name",
        "GeneID",
        "GeneSymbol",
        "HGNC_ID",
        "ClinicalSignificance",
        "ClinSigSimple",
        "LastEvaluated",
        "RS# (dbSNP)",
        "nsv/esv (dbVar)",
        "Origin",
        "OriginSimple",
        "ReviewStatus",
        "NumberSubmitters",
        "TestedInGTR",
        "VariationID",
        "SomaticClinicalImpact",
        "SomaticClinicalImpactLastEvaluated",
        "ReviewStatusClinicalImpact",
        "Oncogenicity",
        "OncogenicityLastEvaluated",
        "ReviewStatusOncogenicity",
    ]
].copy()



location_df = df[
    [
        "#AlleleID",
        "Assembly",
        "ChromosomeAccession",
        "Chromosome",
        "Start",
        "Stop",
        "ReferenceAllele",
        "AlternateAllele",
        "Cytogenetic",
        "PositionVCF",
        "ReferenceAlleleVCF",
        "AlternateAlleleVCF",
    ]
].copy()



allele_df = allele_df.rename(columns={
    "#AlleleID": "allele_id",
    "Type": "allele_type",
    "Name": "allele_name",
    "GeneID": "gene_id",
    "GeneSymbol": "gene_symbol",
    "HGNC_ID": "hgnc_id",

    "ClinicalSignificance": "clinical_significance",
    "ClinSigSimple": "clin_sig_simple",
    "LastEvaluated": "last_evaluated",

    "RS# (dbSNP)": "rs_db_snp",
    "nsv/esv (dbVar)": "nsv_esv_dbvar",

    "Origin": "origin",
    "OriginSimple": "origin_simple",

    "ReviewStatus": "review_status",
    "NumberSubmitters": "number_submitters",
    "TestedInGTR": "tested_in_gtr",

    "VariationID": "variation_id",

    "SomaticClinicalImpact": "somatic_clinical_impact",
    "SomaticClinicalImpactLastEvaluated": "somatic_clinical_impact_last_evaluated",
    "ReviewStatusClinicalImpact": "review_status_clinical_impact",

    "Oncogenicity": "oncogenicity",
    "OncogenicityLastEvaluated": "oncogenicity_last_evaluated",
    "ReviewStatusOncogenicity": "review_status_oncogenicity"
})



location_df = location_df.rename(columns={
    "#AlleleID": "allele_id",
    "Assembly": "genome_assembly",
    "ChromosomeAccession": "chromosome_accession",
    "Chromosome": "chromosome",
    "Start": "start_position",
    "Stop": "stop_position",
    "ReferenceAllele": "reference_allele",
    "AlternateAllele": "alternate_allele",
    "Cytogenetic": "cytogenetic",
    "PositionVCF": "position_vcf",
    "ReferenceAlleleVCF": "reference_allele_vcf",
    "AlternateAlleleVCF": "alternate_allele_vcf"
})

In [5]:
print(allele_df.shape)
print(location_df.shape)

(9048962, 23)
(9048962, 12)

In [6]:
allele_df["allele_id"].nunique()

4558681

In [9]:
allele_df = allele_df.drop_duplicates(subset="allele_id")

In [11]:
allele_df.shape

(4558681, 23)

In [12]:
allele_df["allele_id"].nunique()

4558681

In [13]:
allele_test = allele_df.head(100).copy()

In [15]:
import psycopg

conn = psycopg.connect("host=localhost dbname=clinvar user=postgres password=postgres2026! port=5432")

In [18]:
allele_test = allele_test.astype(object).where(allele_test.notna(), None)

In [20]:
conn.rollback()

In [21]:
with conn.cursor() as cur:
    with cur.copy("""
        COPY allele (
            allele_id,
            allele_type,
            allele_name,
            gene_id,
            gene_symbol,
            hgnc_id,
            clinical_significance,
            clin_sig_simple,
            last_evaluated,
            rs_db_snp,
            nsv_esv_dbvar,
            origin,
            origin_simple,
            review_status,
            number_submitters,
            tested_in_gtr,
            variation_id,
            somatic_clinical_impact,
            somatic_clinical_impact_last_evaluated,
            review_status_clinical_impact,
            oncogenicity,
            oncogenicity_last_evaluated,
            review_status_oncogenicity
        ) FROM STDIN
    """) as copy:
        for row in allele_test.itertuples(index=False, name=None):
            copy.write_row(row)


conn.commit()

### WHOLE DATA UPLOAD

In [22]:
with conn.cursor() as cur:
    with cur.copy("""
        COPY allele (
            allele_id,
            allele_type,
            allele_name,
            gene_id,
            gene_symbol,
            hgnc_id,
            clinical_significance,
            clin_sig_simple,
            last_evaluated,
            rs_db_snp,
            nsv_esv_dbvar,
            origin,
            origin_simple,
            review_status,
            number_submitters,
            tested_in_gtr,
            variation_id,
            somatic_clinical_impact,
            somatic_clinical_impact_last_evaluated,
            review_status_clinical_impact,
            oncogenicity,
            oncogenicity_last_evaluated,
            review_status_oncogenicity
        ) FROM STDIN
    """) as copy:
        for row in allele_df.itertuples(index=False, name=None):
            row = tuple(None if pd.isna(value) else value for value in row)
            copy.write_row(row)


conn.commit()

In [23]:
location_df.columns.tolist()

['allele_id',
 'genome_assembly',
 'chromosome_accession',
 'chromosome',
 'start_position',
 'stop_position',
 'reference_allele',
 'alternate_allele',
 'cytogenetic',
 'position_vcf',
 'reference_allele_vcf',
 'alternate_allele_vcf']

In [24]:
location_test = location_df.head(100).copy()
location_test = location_test.astype(object).where(location_test.notna(), None)

In [25]:
with conn.cursor() as cur:
    with cur.copy("""
        COPY allele_location (
            allele_id,
            genome_assembly,
            chromosome_accession,
            chromosome,
            start_position,
            stop_position,
            reference_allele,
            alternate_allele,
            cytogenetic,
            position_vcf,
            reference_allele_vcf,
            alternate_allele_vcf
        ) FROM STDIN
    """) as copy:
        for row in location_test.itertuples(index=False, name=None):
            copy.write_row(row)


conn.commit()

In [26]:
with conn.cursor() as cur:
    with cur.copy("""
        COPY allele_location (
            allele_id,
            genome_assembly,
            chromosome_accession,
            chromosome,
            start_position,
            stop_position,
            reference_allele,
            alternate_allele,
            cytogenetic,
            position_vcf,
            reference_allele_vcf,
            alternate_allele_vcf
        ) FROM STDIN
    """) as copy:
        for row in location_df.itertuples(index=False, name=None):
            row = tuple(None if pd.isna(value) else value for value in row)
            copy.write_row(row)

conn.commit()

In [27]:
df.shape

(9048962, 43)